### ISSUE TITLE
Пивные худы не работают

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1118]
### Описание

Спамят ошибкой как на скрине. На локалке не воспроизводится, зовите меня для тестов или других админов

### Шаги воспроизведения

1. Зайти на сервер

2. Одеть худы

3. Получить ошибку в консоль и не работающие худы

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/29306eff-3b6b-4380-a491-c5e46b7e1d97)

**Comment by Alwayswannahunt** [comment]
Актуально?

**Comment by Ady4ik** [comment]
@Alwayswannahunt не работают от слова совсем.
Ошибкой более не срет, но не отображает ThistIcons вообще.

**Comment by gogenych** [comment]
актуально. Ошибкой срет но только если есть еще одна кукла на экране

**Comment by ReeZer2** [comment]
Проверено пару минут назад на актуалке на сервере, ошибками не срет.

**Comment by ReeZer2** [comment]
> Проверено пару минут назад на актуалке на сервере, ошибками не срет.

Опять срет

**Comment by Kirus59** [comment]
На локалке баг не воспроизводится
![image](https://github.com/user-attachments/assets/49d895ff-fc54-42f7-b681-cfcc162852ab)
![image](https://github.com/user-attachments/assets/ae9e6f08-0fcf-49b4-a5f0-55b2c7644b32)
![image](https://github.com/user-attachments/assets/10f34261-784b-4e4c-a2ce-7c600bab4ad9)

**Comment by Kirus59** [comment]
На серверах - срет ошибками, уээээээ
