### ISSUE TITLE
Пульт объявления войны не работает

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1120]
### Описание

Пуль соло яо не объявляет войну.

### Шаги воспроизведения

1. Быть соло яо с геймрула
2. Пытаться объявить войну с пульта
3. Плакать, потому что не дают доп тк за войну

### Скриншоты

![Снимок](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/b3c6e42a-0aef-461e-b179-be005c421cc0)

**Comment by AliceValestray** [comment]
Невозможно протестировать из-за невозможности заспавниться на солоЯО на локалке. Скорее всего проблема из-за спавна шаттла.

![Image](https://github.com/SerbiaStrong-220/space-station-14/assets/119437125/2161a9d2-265a-4d7c-9645-3c5226370f73)



![Image](https://github.com/SerbiaStrong-220/space-station-14/assets/119437125/9477e82b-d001-4630-9dcf-ad22d54d19f0)


Делаю смелое предположение, что объявление не делается из-за "прошедшего таймера", поскольку на пульте объявления войны обычных ЯО пишет именно про то, что таймер истёк, хотя с начала раунда вместо надписи "Шаттл может покинуть аванпост!" должен идти 5-минутный таймер для объявления войны.

![Image](https://github.com/SerbiaStrong-220/space-station-14/assets/119437125/97a419bc-5ec9-43c1-9f15-586d7db77a2c)

**Comment by UrPrice** [comment]
Вероятнее всего вызвано смещением системы (mapId) в котором заспавнен лонопа или движением шаттла из-за гридов - из-за чего у пульта срабатывает скрипт "Покинул систему/тронул консоль - проебал возможность объявы"

**Comment by UrPrice** [comment]
Продебажте просто с кодером каким-нибудь процедуру спавна этого mapID, шаттла на них, чтобы понимать какого хуя

**Comment by gogenych** [comment]
Пофикшено этими замечательными людьми https://github.com/SerbiaStrong-220/space-station-14/pull/1164
