### ISSUE TITLE
Бесконечная вместимость переноски

### ISSUE THREAD

**Issue by EstKemran** [SerbiaStrong-220/space-station-14#1121]
### Описание

Большая переноска для животных (PetCarrier) позволяет вместить себя одно entity. Однако, это ограничение, своеобразно, можно обойти, если присутствует ещё одна переноска. Пешку А может взять переноску пешка B, а пешку B может взять в переноску пешка С, и так до бесконечности, пока не закончатся либо пешки, либо переноски.

### Шаги воспроизведения

1. Пешка B засовывает пешку A в переноску.
2. Пешка С засовывает пешку В в переноску.
3. Пешка D засовывает пешку C в переноску.
4. Пешка D несет в руках пешку A, B, C.

**Comment by DexlerXD** [comment]
выдано тестовым заданием
