### ISSUE TITLE
Нерабочая цель ниндзи 220

### ISSUE THREAD

**Issue by 21Melkuu** [SerbiaStrong-220/space-station-14#1122]
### Описание

Не работает взлом криминальный записей для цели нинзди

### Шаги воспроизведения

1. Заспавнить ниндзю
2. Включить перчатки
3. Попытаться взломать
4. Кайфануть 🤙 

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/79728504/b72da14d-effb-45fc-a740-c70109143837)

**Comment by DexlerXD** [comment]
сейчас такой момент есть, что у нас выбор: либо мы ждем интеграции системы криминальных записей оффов под нашу консоль, либо фиксим цель под нашу систему.
но в любом случае, это уже в работе в какой-то степени

**Comment by Alwayswannahunt** [comment]
Закрывайте, забыл упомянуть в https://github.com/SerbiaStrong-220/space-station-14/pull/2072
