### ISSUE TITLE
Нерабочий мессенджер 

### ISSUE THREAD

**Issue by 21Melkuu** [SerbiaStrong-220/space-station-14#1123]
### Описание

Не работает мессенджер, работал хуево когда-то давно маленькое время, а потом вовсе отказался работать.
!Не нужно писать, что все работает, чтобы отправить смс, человек должен зайти хоть раз в мессенджер!

### Шаги воспроизведения

1. Открыть кпк
2. Попробовать отправить текст
3. Кайфануть 🤙 

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/79728504/9c071ab6-eb62-4822-80e3-7b1ad9e23a68)

**Comment by DexlerXD** [comment]
замерджено #1146

**Comment by DexlerXD** [comment]
@gogenych фикс замержен, перенеси в выполненные, пожалуйста
