### ISSUE TITLE
Всё видно в крите

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1126]
### Описание

По словам потерпевшего, он был в крите после убийства пауком и видел всё, как без крита. 

### Шаги воспроизведения

1. Быть положенным в крит пауком(?)

### Скриншоты

![Снимок](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/0962ee66-8ab4-4eff-8b29-0166c3ba3a3d)

**Comment by EstKemran** [comment]
Подтверждаю, случался этот баг при положения меня в крит ЯО, сослался на клиент. Видимо, старый баг вернулся.

**Comment by AliceValestray** [comment]
Белый экран крита не накладывается ни от трогания лампы и падания в крит без эффектов на экране, ни от эффекта сна от паука, ни от эффекта раздваивания экрана от отравления алкоголем. Скорее всего не работает принципиально, поскольку на необновлённой локалке эффект помутнения от крита точно был на экране.

**Comment by gogenych** [comment]
![image](https://github.com/user-attachments/assets/1df8e337-3477-44fc-bc4c-67cfae3660e9)

**Comment by Tris0r** [comment]
не актуально. закрывайте.
