### ISSUE TITLE
Отсутствие нарисованных спрайтов на масок для воксов и Гамлета

### ISSUE THREAD

**Issue by Dinazewwr** [SerbiaStrong-220/space-station-14#1135]
### Описание

Игроки сообщили о проблеме, что если на Гамлета надеть респрайт атмосферного противогаза или сб противогаза, то на Гамлете будет одет спрайт как на человека. Мне нужно, чтобы составили список/таблицу (как удобно) всех спрайтов, у которых отсутствует спрайт для Воксов и Гамлета, чтобы это нарисовать и добавить в игру.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/166321355/8c7e7b1a-c68b-45f6-9d44-61bbc8ebfa6d)

### Шаги воспроизведения

1. Взять Гамлета.
2. Надеть противогаз.
3. Увидеть, что спрайта нет.

ИЛИ

1. Открыть путь space-station-14 -> Resources -> Textures -> Clothing -> Mask 
2. Увидеть, присутствует ли equipped-MASK-hamster и equipped-MASK-vox

_Точно также сделать с путем space-station-14 -> Resources -> Textures -> SS220 -> Clothing -> Mask_

**Comment by OwlMe1steR** [comment]
**Маски для Гамли**

Атмос-противогаз (оба) 
Противогаз СБ 
Противогаз исследователя 
Противогаз капитана 
Противогаз наёмника 
Чёрный боевой противогаз 
Военно-медицинская маска
Грустная маска мима
Испуганная маска мима
Сексуальная маска мима
Синяя маска спецназа

Так же пока проверял у него неправильно отображается баллон плазмы (FYI)

**Маски для Воксов** 

Атмос-противогза (с синим фильтрами) 
Противогаз ОБР
Противогаз наёмника
Противогаз спецназа
Противогаз эскадрона смерти
Банановые маска и парик клоуна
Военно-медицнская маска
Грустная маска мима
Демократиченская маска
Золотая маска клоуна
Испуганная маска мима
Маска Вульфа
Маска Далласа
Маска Морячка
Маска Мужика
Маска Хокстона
Маска Чейнса
Маска ворона
Маска крысы
Маска летучей мыши
Маска лисы
Маска медведя
Маска моли
Маска радости
Маска шакала
Медицинская маска
Синяя маска спецназа

_Надеюсь что ничего не пропустил и лишнего тоже ничего не написал_

**Comment by Alwayswannahunt** [comment]
???
