### ISSUE TITLE
Зомби унатхи, но цвет хвоста не меняется

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1136]
https://discord.com/channels/1097181193939730453/1110976294881083443/1110976294881083443

**Comment by gogenych** [comment]
Старый таск, возможно не актуальный

**Comment by Mishics** [comment]
Так всё ещё это, ты шоу
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/113888808/eda4e94b-a08b-4574-90d9-b32dd1e7af72)

**Comment by Mishics** [comment]
+если использовать имплант ДНК миксер после обращения, ты становишься как обычная кукла, но всё ещё зомби
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/113888808/b9fbe374-6949-4440-909b-b250d3101e4a)
