### ISSUE TITLE
Пофиксить баг получения урона от неписей через контейнеры, шкафы

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1140]
"Описание
Пауки могут кусать через контейнеры, шкафы пока ты в них, хотя это не логично сначала должен ломаться шкаф, а не умирать игрок.
Репродукция
Спрятаться в шкаф от паука который вас преследует и наблюдать свою смерть."
https://discord.com/channels/1097181193939730453/1134423225418403910

**Comment by Mishics** [comment]
Старый баг, уже всё
