### ISSUE TITLE
Цели антагониста

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1141]
### Описание

Цели трейтора не даются ему при некоторых, не совсем понятных условиях. Возможно конфликтуют с друг другом.

### Шаги воспроизведения

1. Дать антагу цели (особенно если у него уже есть)

**Comment by DexlerXD** [comment]
да там перебирать цели друг с другом надо, там на несколько часов засесть можно

**Comment by gogenych** [comment]
ваще это фича, не думаю что мы будем рефакторить цели антагов ради такого
