### ISSUE TITLE
Руки перепутаны

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1148]
### Описание

Минорный баг, ни на что не влияет. Хрен знает как вызвать 

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/4f34850d-2b40-411b-98fe-8d82b7aedee9)

**Comment by gogenych** [comment]
Проблема поймана, виноваты феленидамы
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/6b7dca0c-4bd5-4955-ba50-9ec63a7c9b11)

**Comment by UrPrice** [comment]
Залил фикс в PR https://github.com/SerbiaStrong-220/space-station-14/pull/1152

**Comment by gogenych** [comment]
> Залил фикс в PR #1152

оп, спасибо, закрываю.
