### ISSUE TITLE
Вставая с медкровати застреваешь. 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1149]
### Описание

Вот этот пул https://github.com/SerbiaStrong-220/space-station-14/pull/1113 сломал мед кровати и криоподы и всё что там затронуто 

Вставая с кровати ты встаёшь всегда на север, если на севере есть стена, то ты застреваешь между кроватью и стеной. 

### Шаги воспроизведения

1. Поставить кровать к югу от стены

2. Лечь на нее и встать

3. Обнаружить себя зажатым

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/f9e8aa6d-79eb-4b12-ac67-d8796ca9f23a)

**Comment by gogenych** [comment]
@Ady4ik критический баг твоего пула

**Comment by OwlMe1steR** [comment]
Также имеется проблема с кроватью (включая стазисную). 
Если их открепить и начать ходить рядом, они будут прилепать к кукле.

Наглядно: https://www.youtube.com/watch?v=wP_65Pmp-bM
