### ISSUE TITLE
Дрифт утильским шаттлом

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1153]
### Описание

Кажется если открутить гироскоп во время бсс, шаттл сделает резкий поворот. 

### Шаги воспроизведения

1. Нажать БСС
2. Открутить в процессе гироскоп

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/d7f6113b-d43a-413e-814c-25850d54cbec)

**Comment by gogenych** [comment]
есть еще такое мнение
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/67a14084-95ab-46d5-884d-cdd9d2b482d4)

**Comment by OwlMe1steR** [comment]
**Итоги тестирования**

Поигрался с гироскопом, пытаясь развернуть утильский шаттл.

1)Просто выключить гироскоп.
2)Вращать утильский шаттл с включённым гироскопом.
3)Открутить гироскоп.
4)Открутить гироскоп и прикрутить его в другом месте.

Итог: утильский шаттл прилетал нормально.

Однако его можно развернуть, если перед моментом БСС прыжка заранее установить его положение (скриншот для примера прикреплён). Конечно, это ломает камеру на всю экспедицию, и заход в "подземелье" не решает проблемы с камерой.

![Image](https://github.com/SerbiaStrong-220/space-station-14/assets/170038943/299fe434-758b-4353-bec8-36e274e81a14)

**Comment by Ady4ik** [comment]
Неактуально
