### ISSUE TITLE
Тележка уборщика застревает в перилах

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1154]
### Описание

Тележка уборщика имеет куда больший хитбокс чем текстуру, из-за чего застревает. 

Так же создал[ ишью оффам](https://github.com/space-wizards/space-station-14/issues/29089), кто первый пофиксит зальет другому 

https://discord.com/channels/1097181193939730453/1251845802364502078/1251845802364502078
### Шаги воспроизведения

1. Толкать тележку уборщика через узкие места с перилами

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/42ba2a5c-d89e-405a-9402-73c4e1f524e4)

**Comment by EstKemran** [comment]
https://github.com/SerbiaStrong-220/space-station-14/pull/1155

**Comment by gogenych** [comment]
> #1155

увидел, спасибо.
