### ISSUE TITLE
Пофиксить баг автовыделения определенной области в режиме удаления

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1161]
**Воспроизведение**: При нажатии кнопки удаления в Спавне сущностей при зажатом ctrl наводимся на один из админских значков (значок песочницы; значок ahelp и т.д, либо же наводимся на чат. Результат: выделяется определенная область для удаления, что может послужить удалением половины карты, при быстром выделении области удаления и случайном нажатии.

UPD: issue у оффов

**Comment by gogenych** [comment]
@OwlMe1steR Нужны тесты

**Comment by OwlMe1steR** [comment]
### **Итоги теста**

При зажатом Ctrl (выбор области для удаления) и наведении на любую панель (UI) выделяется огромная область в случайную сторону (скриншот прикреплён). 
Однако панель не даёт удалить то, что было выделено. Нужно вернуть курсор обратно на игровой экран, и тогда выделится новая область от заданной изначально точки до курсора.

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/170038943/e19b7e09-56cf-4b94-9923-bacc5c5ae1af)

_Доп. комментарий_

Сообщите, если нужно записать видео для более подробной демонстрации.
