### ISSUE TITLE
ТТС не рандомится 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1165]
### Описание

Миксер ДНК заменяет голос на "отца Григория", хотя должен заменяться на рандомный. Предположительно работает только на мужской кукле, нужны тесты

https://discord.com/channels/1097181193939730453/1252349694924034098/1252349694924034098

### Шаги воспроизведения

1. Быть с любым голосом
2. Вколоть миксер ДНК

**Comment by AliceValestray** [comment]
Миксер ДНК меняет всё, кроме черт (убирает их) и голоса (ставит ТТС Отца Григория).

![Image](https://github.com/SerbiaStrong-220/space-station-14/assets/119437125/b3de0102-aece-4144-a199-1fec7157e93f)

Желательно бы вместе с фиксом голоса ещё добавить рандомизатор черт из определённой категории. Крылья ниан, капюшоны/рога унатхов, итд.
