### ISSUE TITLE
Крики в рацию не перебиваются 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1168]
### Описание

Если писать чат и получить урон, реплика прервется, а вот если писать в рацию и получить урон, реплика не прирывается.

https://discord.com/channels/1097181193939730453/1251951832063021268/1251951832063021268

### Шаги воспроизведения

1. Писать в рацию
2. Получить урон 

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/ea2eb1c3-63fa-44a1-9e0c-03814a1985cf)

**Comment by AliceValestray** [comment]
Это правда, урон прерывает обычную речь и шёпот, а эмоции, чат мёртвых, LOOC и **рацию** - нет.


![Image](https://github.com/SerbiaStrong-220/space-station-14/assets/119437125/992e0207-8e2f-4ed0-9e2e-7bcea6fb8311)



![Image](https://github.com/SerbiaStrong-220/space-station-14/assets/119437125/3649ac3b-d97f-4000-a2bd-1ae5e7e1bbee)
