### ISSUE TITLE
Амбузол

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1173]
### Описание

Амбузол не лечит нулевых пациентов (а надо?), и простых заражённых от укуса (возможно исправили)

https://discord.com/channels/1097181193939730453/1236482815604818012/1236482815604818012
### Шаги воспроизведения

1. Заразиться зомби-вирусом -> 2. Кайфовать от отсутствия результата

**Comment by Alwayswannahunt** [comment]
Так возможно или исправили?

**Comment by Tris0r** [comment]
**Протестировал**
Амбузол не спасает, если ты нулевой ( и не должен ). Но если ты заражен, то амбузол не даст тебе стать зомби.

**Comment by Ady4ik** [comment]
Нулевых и не должно лечить.
Если лечит укушенных - тогда нормально.
