### ISSUE TITLE
Синди-слова

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1174]
### Описание

В редких случаях слова агентов синдиката не совпадают с друг-другом, что мешает людям.

https://discord.com/channels/1097181193939730453/1235307171798061068/1235307171798061068

### Шаги воспроизведения

1. Получить кодовые слова -> 2. Увидеть кодовые слова другого агента

**Comment by Alwayswannahunt** [comment]
![изображение](https://github.com/user-attachments/assets/2834498b-f01f-4f00-a623-8901c9f8eaa9)
