### ISSUE TITLE
Маскировка

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1177]
### Описание

При попытке замаскироваться под любой автомат, шкаф (главы или с одеждой), протолат/автолат - маскировка изображает разобранную версию объекта (с открытой крышкой, выключенным, более светлой версии и тп)

### Шаги воспроизведения

1. Использовать маскировочное устройство на автомате -> 2. Увидеть неправильную маскировку

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/113888808/c35c8937-576f-4c64-8563-b0194fdc39b4)

**Comment by stalengd** [comment]
Скорее всего регрессия после #2152

**Comment by stalengd** [comment]
Дубликат #1502
