### ISSUE TITLE
Слаймолюды и голод

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1178]
### Описание

Если голодный слаймолюд поменяет форму на слайма - его голод и жажда не перейдут к слайму, и тот будет (если обратно стать слаймолюдом всё возвращается)

### Шаги воспроизведения

1. Находим голодного слаймалюда -> 2. перевоплощаемся в слайма -> 3. Наблюдаем за отсутствием голода

**Comment by Alwayswannahunt** [comment]
Закрывайте, если и у нас герасов вырежут
