### ISSUE TITLE
Вещи сквозь ящики

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1182]
### Описание

Если открыть инвентарь сумки и затем кинуть её в ящик закрыв его - мы всё ещё сможем брать вещи из сумки

https://discord.com/channels/1097181193939730453/1229457610407804999/1229457610407804999

### Шаги воспроизведения

1. Открыть сумку и поместить её в ящик -> 2. Закрыть ящик и увидеть баг

**Comment by DexlerXD** [comment]
Выдал тестовым заданием

**Comment by DexlerXD** [comment]
Пофикшено оффами на апстриме
