### ISSUE TITLE
Карпы

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1183]
### Описание

Карпы и другие животные могут вытаскивать что-либо из мусорки и бить как мили оружие (считаю это механом)

### Шаги воспроизведения

1. Нажать на мусорку ПКМ -> 2. Выбрать "Извлечь"
1. В режиме боя нажать ПКМ

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/113888808/1acd53e8-3310-495e-a96e-8e5f7c6c5d65)

**Comment by Tris0r** [comment]
Неактуально.
