### ISSUE TITLE
Квадроциклы на льду

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1186]
### Описание

Если на Т/С залететь на лёд - оно разгоняется до больших скоростей (хотя звучит логично?)

https://discord.com/channels/1097181193939730453/1219951366487937034/1219951366487937034

### Шаги воспроизведения

1. Заехать квадроциклом на лёд -> 2. Разогнаться

**Comment by Ady4ik** [comment]
В целом логично, так как тут присутствует эффект скольжения. Закрываю.
