### ISSUE TITLE
Помидор-убийца оружие

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1191]
### Описание

Тело помидора убийцы оружие. Всё

https://discord.com/channels/1097181193939730453/1250597512029536337/1250597512029536337

### Шаги воспроизведения

1. Взять труп помидора убийцы -> 2. Бить им на ЛКП/ПКМ

**Comment by Ady4ik** [comment]
Невозможно исправить в связи с тем, что все ентити, которые имеют урон (в данном случае помидор-убийца) воспринимаются системой как MeleeWeapon (т.к NPC не умеют включать и выключать комбат мод) и, как следствие, могут быть использованы хуманусом для того, чтобы драться.
Слишком глубоко лезть, так что скорее всего с такими запросами только к оффам
