### ISSUE TITLE
Спрайт РПГ-7

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1192]
### Описание

Если стрелять с РПГ-7, даже при отсутствие ракеты в ней - в руках куклы будет как-будто заряженная пушка

### Шаги воспроизведения

1. Вытащить снаряд из РПГ-7

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/113888808/28d0b025-9fd3-49b1-95ef-42f4787ff249)

**Comment by EstKemran** [comment]
Спрайты инхандов без ракеты внутри - присутствуют в игре.

Проблема именно в отображении этих слоёв. 

Проблема в отсутсивия отображение кол-ва оставшегося боеприпаса присутсвует на всех таких типах прототипов. _(От импульсного карабина ОБР и лазера Кэпа до свалинна и станнера)_
