### ISSUE TITLE
Спящие мишени 

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1199]
### Описание

Если усыпить жертву и никак не целиться в неё стреляя рядом с ней - пуль будут попадать, как буд-то они стоит на ногах

### Шаги воспроизведения

1.  Усыпить куклу -> 2. Начать стрелять вокруг неё

**Comment by OwlMe1steR** [comment]
**### Итоги теста**

Если усыпить куклу и начать стрелять в неё, то хитбокс у куклы остаётся как у стоячей. 
Проверил стрелковое оружие (летальное и нелетальное), а также броски разных предметов, как например копьё (оно застрянет в воздухе и нанесёт урон кукле).
