### ISSUE TITLE
Микроволновка и готовка

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1211]
### Описание

Во время работы микроволновки может мигать свет автоматом оканчивая готовку - из-за этого приготовление мясных блюд затруднительно, ведь при окончание такой готовки место блюда вылетают ингредиенты и горячий стейк 

### Шаги воспроизведения

1. Поставить готовиться что-то с мясом -> 2. Включить и выключить свет -> 3. Поглядеть за багом

**Comment by OwlMe1steR** [comment]
### **Итоги теста**

При приготовлении сырого мяса с чем-либо, через 5 секунд мясо приготовится. Если после этого отключится электричество, то из микроволновки выпадет готовый стейк, а все остальные компоненты останутся внутри.

**Comment by gogenych** [comment]
фича полагаю
