### ISSUE TITLE
Выбираемся из мусорки, пока спим или в стане.

### ISSUE THREAD

**Issue by OwlMe1steR** [SerbiaStrong-220/space-station-14#1213]
### Описание

После усыпления ноктюрином или иными усыпляющими химическими веществами и запихивания куклы в мусорку, при использовании клавиш передвижения, кукла может выбраться из мусорки. 
Также это работает, если отправить куклу в стан с помощью станнеров или дубинки.

### Шаги воспроизведения

1. Взять гипоспрей или гипоручку и заполнить ноктюрином / взять станнер или дубинку.
2. Вколоть содержимое в куклу / довести куклу до стана.
3. Засунуть куклу в мусорку.
4. Перейти за куклу и нажать клавиши передвижения.

**Comment by Alchidot00** [comment]
Можете посмотреть мой багфикс?

**Comment by DexlerXD** [comment]
https://github.com/SerbiaStrong-220/space-station-14/pull/1243
