### ISSUE TITLE
Патронташ 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1216]
### Описание

При надетом патронташе вылезают модельки патронов, которые вставлены в сам патронташ, их можно взять (1-3 скрины). Более того, даже снимая патронташ они не пропадают и продолжают вылезать (4 скрин).

Предположу что это связано с тем, что патронташ забагал и заряжался патронами сверху даже когда был заполнен (заметил что в него поместилось как минимум две коробки патронов), поэтому они вылезают.

https://discord.com/channels/1097181193939730453/1254928108461621311/1254928108461621311

### Шаги воспроизведения

1. Одеть патронташ
2. зарядить его
3. Поводить мышкой по текстуре куклы и найти торчащий патрон

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/5d06996c-df62-4d96-9c31-bbec1cdec4ac)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/6897b16e-ab0d-440c-8b30-4665ad38399d)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/ed693370-3598-48ce-b88a-a6d017f7df1d)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/3e1d6794-3486-4bf0-b71e-bde2c955206d)

**Comment by OwlMe1steR** [comment]
### **Итоги теста**

Данный баг удалось реализовать только через раздатчик ружейных патронов (через все). В итоге неограниченное количество патронов может застрять в кукле, и она всегда будет носить с собой патроны, даже если будет голой.

В ходе теста также обнаружилась проблема, если использовать пустой патронташ на объект, который можно заполнить патронами (другой патронташ, силовик, коробку и т.д.), то пустой патронташ больше никогда нельзя будет зарядить. В связи с этим патронташ ломается.

В итоге, со сломанным патронташем, патроны не вставляются в него, а закрепляются на кукле.

**Comment by Tris0r** [comment]
Неактуально.
