### ISSUE TITLE
Кровати и голые куклы

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1220]
### Описание

1. Если лечь на кровать с каким-то шансом кукла будет отображаться голой

2. Если поднять куклу с кровати (руками другой куклы) она застрянет

### Шаги воспроизведения

1. лечь на кровать

2. поднять другим персонажем

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/25c7a801-d6ea-4f5a-b185-a1531ed3c1d6)

**Comment by gogenych** [comment]
связано с 
https://github.com/SerbiaStrong-220/space-station-14/pull/1196

**Comment by Ady4ik** [comment]
@TheArturZh need ur opinion

**Comment by OwlMe1steR** [comment]
### **Итоги теста**

Что ж, будет много текста, но постараюсь объяснить все понятно.

Из-за одного бага было обнаружено ещё 4, в итоге у нас 5 багов и их описание. Давайте по порядку, начнём с того, который нас собрал.

1) Проблема с отображением кукол на кроватях, где они уже давно не лежат (я буду называть это, момент XR). 

Когда кукла A находится в зоне прогрузки (для момента XR достаточно около 10 тайтлов), а кукла B ложится на кровать, кукла A уходит на небольшое расстояние (Происходит момент XR, система запомнила, что кукла B лежит на кровати). После этого кукла B открепляется с кровати и уходит в противоположную сторону, чтобы не попасть в зону прогрузки куклы A. Когда кукла A возвращается, кукла B может оказаться голой на кровати. Иногда вместо имени куклы может отображаться "???" (Имя куклы: ???). Если вы находитесь в гостах, Вы можете видеть, как голая кукла ведёт себя, разговаривает и выполняет действия, хотя на самом деле её там нет.
Простыми словами, проблема заключается в том, что система прогрузки вокруг куклы A запоминает, что кукла B легла на кровать, но забывает убрать её после того, как кукла B уходит.

Решение этой проблемы пока не найдено, кроме как встречей куклы A с куклой B или попаданием в зону прогрузки.


**Перейдём к другим багам**


2) Если слаймолюд переходит в режим Гераса, будучи лежащим на любой кровати (больничной, паутинной, обычной, стазисной), кукла остаётся в состоянии кататона на кровати, в то время как игрок в режиме Гераса может свободно перемещаться, и даже не пропадёт с кровати, если уйдёт на достаточно большое расстояние и вернётся в первоначальную форму.

3) Если кукла A открепляет куклу B с кровати (ПКМ -> Открепить), кукла A заберётся на эту кровать.

4) Невозможность перезакрепить куклу с одной кровати на другую. Система показывает сообщение о том, что кукла уже закреплена. Однако в результате будет происходить действие с лежащей куклой (мы будет помогать ей забраться на другую кровать как на стол), но в итоге просто открепляется с изначальной.

5) Если медленно отодвигать куклу с кровати (Ctrl + ЛКМ), в какой-то момент она может застрять и оказаться за кроватью и быть зажатой стенкой.

_Доп. комментарий_

Если нужно более подробное описание, дайте знать, я постараюсь сформулировать проще и запишу откаты.

Также я не уверен, касается ли это только кроватей, но я также провёл тесты с "Инвентором квантового спина".

6) Если лежать на кровати и использовать "Инвентор квантового спина", кукла телепортируется к второму устройству и пролетает через всю станцию (кроме космоса), пока не достигнет кровати.

**Comment by gogenych** [comment]
> ### **Итоги теста**
> Что ж, будет много текста, но постараюсь объяснить все понятно.
> 
> Из-за одного бага было обнаружено ещё 4, в итоге у нас 5 багов и их описание. Давайте по порядку, начнём с того, который нас собрал.
> 
> 1. Проблема с отображением кукол на кроватях, где они уже давно не лежат (я буду называть это, момент XR).
> 
> Когда кукла A находится в зоне прогрузки (для момента XR достаточно около 10 тайтлов), а кукла B ложится на кровать, кукла A уходит на небольшое расстояние (Происходит момент XR, система запомнила, что кукла B лежит на кровати). После этого кукла B открепляется с кровати и уходит в противоположную сторону, чтобы не попасть в зону прогрузки куклы A. Когда кукла A возвращается, кукла B может оказаться голой на кровати. Иногда вместо имени куклы может отображаться "???" (Имя куклы: ???). Если вы находитесь в гостах, Вы можете видеть, как голая кукла ведёт себя, разговаривает и выполняет действия, хотя на самом деле её там нет. Простыми словами, проблема заключается в том, что система прогрузки вокруг куклы A запоминает, что кукла B легла на кровать, но забывает убрать её после того, как кукла B уходит.
> 
> Решение этой проблемы пока не найдено, кроме как встречей куклы A с куклой B или попаданием в зону прогрузки.
> 
> **Перейдём к другим багам**
> 
> 2. Если слаймолюд переходит в режим Гераса, будучи лежащим на любой кровати (больничной, паутинной, обычной, стазисной), кукла остаётся в состоянии кататона на кровати, в то время как игрок в режиме Гераса может свободно перемещаться, и даже не пропадёт с кровати, если уйдёт на достаточно большое расстояние и вернётся в первоначальную форму.
> 3. Если кукла A открепляет куклу B с кровати (ПКМ -> Открепить), кукла A заберётся на эту кровать.
> 4. Невозможность перезакрепить куклу с одной кровати на другую. Система показывает сообщение о том, что кукла уже закреплена. Однако в результате будет происходить действие с лежащей куклой (мы будет помогать ей забраться на другую кровать как на стол), но в итоге просто открепляется с изначальной.
> 5. Если медленно отодвигать куклу с кровати (Ctrl + ЛКМ), в какой-то момент она может застрять и оказаться за кроватью и быть зажатой стенкой.
> 
> _Доп. комментарий_
> 
> Если нужно более подробное описание, дайте знать, я постараюсь сформулировать проще и запишу откаты.
> 
> Также я не уверен, касается ли это только кроватей, но я также провёл тесты с "Инвентором квантового спина".
> 
> 6. Если лежать на кровати и использовать "Инвентор квантового спина", кукла телепортируется к второму устройству и пролетает через всю станцию (кроме космоса), пока не достигнет кровати.

@Ady4ik upd

**Comment by UrPrice** [comment]
Есть ощущение, что проще откатить первоначальное изменение кроватей
