### ISSUE TITLE
Облысение ГСБ от скафа

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1230]
### Описание

Шлем в скафандре ГСБ вызывает облысение

https://discord.com/channels/1097181193939730453/1255939629128093718/1255939629128093718

тут есть видео:
https://discord.com/channels/1097181193939730453/1220096530782879964/1220096530782879964

### Шаги воспроизведения

1. Иметь волосы и скафандр ГСБ
2. Нацепить шлем скафандра
3. Лишиться волос

**Comment by OwlMe1steR** [comment]
### **Итоги теста**

Попытался воспроизвести баг на 4 разных расах с разными масками, как было описано в баге. Но в итоге не получилось.

Если баг повторится, потребуется больше информации, например какая маска была, что происходило и т.д.

**Comment by gogenych** [comment]
починили
