### ISSUE TITLE
Ковёр и шторы

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1236]
### Описание

Если положить ковер на шторы пропадет весь стак, а не одна штука

https://discord.com/channels/1097181193939730453/1256124158526488688/1256124158526488688

### Шаги воспроизведения

1. Положить стак ковра в тайл с шторами

**Comment by NightmareStalker** [comment]
Из-за трекера не по форме ишуй понят не так. Говорилось про крафт.

**Тест на крафт:**
- на стол с простынью из ковров кладется фулл пачка ковров - 2-10-стак ковра
- при крафте штор уходит также вся пачка - 2-10-стак

**Тест на то, как понял Гогеныч:**
 - на пол кладется по одному ковру, но сами ковры можно накладывать друг на друга до бесконечности
 
**Итог:**
- Так быть не должно. До 30 штук ковра безлимитно на одну штору/простынь красивого стола - жирно. Должно быть 1-2 ковра на крафт одной шторы и 1-2 ковра на покрытие стола простынью.

**Демонстрация на крафт:**

https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/2c0568bf-ba84-4c0c-9588-beacda1136e0


https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/31843470-5fd6-4a28-b3ef-0459ac7a32d1
