### ISSUE TITLE
Редактор персонажей немного сломался

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1240]
### Описание

1) Не появляется возможность сохранить некоторые изменения персонажа сами по себе. В список входят:
Добавление волос
Добавление лицевой растительности
Выбор причёски
Выбор цвета причёски
Выбор лицевой растительности
Выбор цвета лицевой растительности
Настройка цвета глаз
Галочка о телепортации в крио хранилище при длительном ССД

Стоит подметить что цвет кожи/шерсти/чешуи при этом сохраняется, что выглядит подозрительно, думаю оффы таким образом борются с расизмом.

2) Размер феленидов редакторе не соответстсвует размеру в игре

3) Уши и хвосты феленидов в вкладке черты названы Плейсхолдерами.  Хуй поймешь какой хвостик полосатый а какой в пупырку

4) У феленидов нет вкладок для черт:
Голова
Морда
Грудь
Руки
Ноги
Наложение

Из-за чего большая часть оффовских черт не работает на феленидов

Также некоторые вкладки отсутствуют у слаймолюдов, видимо им по какой-то причине нельзя бинты носить(за то комбинезоны можно, ага, конечно)

**Comment by OwlMe1steR** [comment]
### **Итоги теста**

Ниже приведены проблемы разных рас в редакторе персонажей.

**Человек**

1. При изменении голоса на какой-либо и обратно кнопка "сохранить" застревает и показывает, что можно сохранить, хотя голос уже поставлен обратно.
2. При изменении, удалении и добавлении причёски кнопка "сохранить" не работает.
3. При изменении, удалении и добавлении лицевой растительности кнопка "сохранить" не работает.
4. При изменении RGB (HSV) волос, лицевой растительности и цвета глаз кнопка "сохранить" не работает.
5. При изменении приоритетности с "Получить должность "пассажир", если должность недоступна" на "Остаться в лобби, если должность недоступна" кнопка "сохранить" не работает.
6. При установке или снятии галочки на "Телепортация в крио-хранилище при длительном ССД" кнопка "сохранить" не работает.

**Арахниды**

1. Похожие проблемы, что и в пунктах (1, 4, 5, 6) в описании проблем человека.
2. Отсутствие в чертах рук "Аугментация" (роборуки) _*возможно так и задумано_.

**Слаймолюды**

1. Похожие проблемы, что и в пунктах (1, 2, 3, 4, 5, 6) в описании проблем человека.
2. Отсутствие черты "Морда" и наложения (бинты) в чертах внешности _*возможно так и задумано_.

**Фелиниды**

1. Похожие проблемы, как и в пунктах (1, 2, 3, 4, 5, 6) в описании проблем человека.
2. При выборе фелинидов рост не изменяется, остаётся человеческого роста.
3. У Фелинидов отсутствуют почти все черты внешности, имеются только: Голова (верх), Руки и Хвост _*возможно так и задумно_.
4. У Фелинидов хвосты подписаны как "marking-FelinidTails [x]", что не позволяет понять, какой хвост выбирается, пока не откроется окно RGB. Даже так, "marking-FelinidTails" и "marking-FelinidTails [2]" выглядят похоже, хотя под номером [2] это полосатый хвост.

_Доп комментарий_

В рассах таких как Дворфы, Нианы, Унатхки, Дионы также имеются общие проблемы, а именно...
Похожие проблемы, как и в пунктах (1, 2, 3, 4, 5, 6) в описании проблем человека.
