### ISSUE TITLE
Цель украсть cargo shuttle console board не засчитывается

### ISSUE THREAD

**Issue by vakuor** [SerbiaStrong-220/space-station-14#1249]
### Описание

Цель украсть `cargo shuttle console board` не засчитывается, хотя у тебя в инвентаре может быть `консоль управления шаттлом (консольная плата)`

### Шаги воспроизведения

1. Получить цель "Украсть cargo shuttle console board"
2. Получить "консоль управления шаттлом (консольная плата)"
3. Увидеть невыполнение цели

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/19931959/16ac8a51-5cc7-4abd-99eb-83962d53ee5e)

**Comment by Kirus59** [comment]
Мне кажется тут скилл ишуе, т.к. цель именно на плату консоли управления КАРГОшаттлом, о не обычную

**Comment by Kirus59** [comment]
Ну и по id все сходится
![Screenshot_20240630_054741_Chrome](https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/f3284230-3623-4d3a-b606-9a3f9f146dd7)
![Screenshot_20240630_054801_Chrome](https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/ab6f3925-a04b-46bf-9b96-116b1aed39de)

**Comment by vakuor** [comment]
@Kirus59 Можешь проверить это в игре? Меня смущает, что cargo shuttle console board в принципе не имеет перевода на ру. Мб баг все же где-то есть.

**Comment by Kirus59** [comment]
> @Kirus59 Можешь проверить это в игре? Меня смущает, что cargo shuttle console board в принципе не имеет перевода на ру. Мб баг все же где-то есть.

Перевод то есть, это сломалась именно локализация в цели (и не только у этой цели, вроде во всех целях на кражу у аоров не работает локализация)
![Screenshot_20240630_145557_Chrome](https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/1533f4f4-f70b-4e45-a15c-a16ce5f3eefe)

**Comment by vakuor** [comment]
> Перевод то есть, это сломалась именно локализация в цели (и не только у этой цели, вроде во всех целях на кражу у воров не работает локализация)
А можешь глянуть выполнение цели? Я бы сам попробовал, но не шарю, как выдать себе цель и предмет

**Comment by Kirus59** [comment]
Я смогу это проверить только завтра вечером, раньше никак.
По поводу выдачи - через пкм выдаёшь своей кукле антажку (конкретно вора) а потом пишешь команду:
`addobjective [твой сикей] CargoShuttleCircuitboardStealObjective`
(Только не на ролях карго, она им не выдастся)

**Comment by vakuor** [comment]
Отбой, работает. Надо было положить в карманы.
Значит надо просто перевод цели добавить.

**Comment by Kirus59** [comment]
Уверен что цели вообще работают на дебаг сборке?

**Comment by Kirus59** [comment]
А ок, сообщения не заметил последнего)

**Comment by gogenych** [comment]
Перевели в другое ишью https://github.com/SerbiaStrong-220/space-station-14/issues/1258 это закрываю
