### ISSUE TITLE
Турель не работает

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1251]
### Описание

 Турель из ящика инструментов не наводилась на цели и следовательно не стреляла. Баг не удаётся воспроизвести, но он реально существует, был замечен несколькими людьми независимо 
 
 https://discord.com/channels/1097181193939730453/1256527579318456340/1256527579318456340

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/417c3c91-665b-40d3-90d4-a1c2da1b142a)

**Comment by Kirus59** [comment]
Баг не с турелью, а с ИИшкой (по словам людей с раунда). В раунде все мобы с ИИ ломались и не двигались.

**Comment by gogenych** [comment]
оффы
