### ISSUE TITLE
Зомби, слаймы, пауки, карпы и прочие могут смываться

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1252]
### Описание

Зомби, слаймы, пауки, карпы и прочие управляют мусоркой через пкм. В целом, запретить им это не сложно, но возникнет проблема, ибо они сами тогда не смогут выбраться из мусорки. В идеале придумать альтернативный способ выхода из мусорного ведра. 

https://discord.com/channels/1097181193939730453/1256338958678495302/1256338958678495302

### Шаги воспроизведения

1. Быть чем угодно без рук
2. Пкм на мусорку

### Скриншоты

видос в дискорде

**Comment by Tris0r** [comment]
Неактуально. Закрываем @stalengd
