### ISSUE TITLE
Госты не могут читать записки и интерактить с UI объектами

### ISSUE THREAD

**Issue by UrPrice** [SerbiaStrong-220/space-station-14#1260]
### Описание

Будучи гостом ты не сможешь ни прочитать записку, ни открыть какую-либо консоль, ни посмотреть в чужое КПК. Иногда хочется просто понаблюдать в спектаторах, почекать записки и т.д.

### Шаги воспроизведения

1. Зайти за госта без aghost.
2. Попробовать интерактить с предметами
3. Разочароваться

**Comment by AliceValestray** [comment]
Такое имеется, раньше можно было через Е открыть и прочитать записку, как пример, сейчас же не работают ни бинды, ни меню через ПКМ со всеми доступными кнопочками "переключить UI", "переключить интерфейс", и так далее.

**Comment by Alwayswannahunt** [comment]
Починено в апстриме на момент 18:23 05.07.2024
