### ISSUE TITLE
Ломанные лодауты ОСЩ и утилей

### ISSUE THREAD

**Issue by EstKemran** [SerbiaStrong-220/space-station-14#1264]
### Описание

Нельзя выбрать снаряжение для ОСЩ и утилизатора в персонализации персонажа. Кнопка снаряжение не работает.

## Нужны тесты

Я смог воспроизвести этот баг единожды на лодауте ОСЩ (Переключался между персонажами, и тыкал кнопку снаряжение). После этого, сколько бы не пытался, не получается ни на ОСЩ, ни на утиле. Тестеры, посмотрите пожалуйста :gonnacryhampter: 

### Шаги воспроизведения

1. Зайти в меню персонализации
2. Нажать на "снаряжение" ОСЩ/утилизатора
3. Лодаут не открывается

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/8f20a0a1-776d-4e63-816d-3f82894f025e)

**Comment by Alwayswannahunt** [comment]
Это баг вылазит после обновления нами лодаутов - добавил/поменял что-то в нём и при этом, например, раньше выбора перчаток не кэпе не было, а тут раз и добавили, то ты получишь этот баг. Лечится установкой приоритета роли на высокую (выставляет на лодауте стандартные значения), что позволяет решить проблему

**Comment by gogenych** [comment]
не воспроизводится
