### ISSUE TITLE
Не выкидывает в лобби на локальном сервере

### ISSUE THREAD

**Issue by NightmareStalker** [SerbiaStrong-220/space-station-14#1270]
### Описание

При создании нового персонажа у него в должности дефолтно становится пункт "Спавнить пассажиром, если не доступна должность". Это на локальном сервере не дает после перезапуска раунда выйти в лобби с редактором персонажа - появляешься сразу на Дев карте.

### Шаги воспроизведения

1. Создать нового персонажа для тестов
2. Не менять пункт про спавн
3. Зайти персонажем
4. Открыть админ-меню(F7) - Раунд - Перезапустить сейчас
5. В лобби не кикнет

### Скриншоты

Как есть на рандомном персонаже:

https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/778ba781-bf6e-400d-becf-8f5ca41376d1

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/68f604c1-baac-48c8-9308-7b1535c40045)

Как должно быть на рандомном персонаже:

https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/d464c971-f10d-41ef-a5bc-80f199a2e929

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/67befddc-4660-4671-85a8-0e241f96a688)

**Comment by Kirus59** [comment]
Решение: использовать Release билд для таких тестов :Clueless:
