### ISSUE TITLE
Спавн двух тесл

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1315]
### Описание

С каким-то, предположительно низким, шансом спавнятся две теслы сразу при определенных условиях настройки УЧ.

### Шаги воспроизведения

1. Включаем уч на первом уровне 
2. Ждем когда УЧ произведет три выстрела по мишени
3. После третьего выстрела сразу переключаем на третий уровень 
4. Итог получаем два тесла бола.....

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/7b13714c-78b3-401e-85c3-0a83600ed5ad)

**Comment by AliceValestray** [comment]
Протестировано доверенным мальчиком-инженерчиком Сомнией: баг не воспроизводится ни на одной из карт, ни по трекерам, ни с разными уровнями УЧ. Возможно, проблема на сервере и её стоит проверить старшим разработчикам, либо вовсе починено само собой.
