### ISSUE TITLE
Дракон и карпы не активируют мины

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1326]
### Описание

Взрывная мина не активируется драконом и карпами и возможно другой фауной. 

### Шаги воспроизведения

1. поставить мину
2. зайти на нее драконом

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/dbf2579b-cecc-4d29-bd69-bc769a844ba0)

**Comment by Kit0vras** [comment]
Не слишком понимаю, как летающий карп и дракон могут активировать мину, находящуюся НА ЗЕМЛЕ

**Comment by gogenych** [comment]
> Не слишком понимаю, как летающий карп и дракон могут активировать мину, находящуюся НА ЗЕМЛЕ
логично, закрываю
