### ISSUE TITLE
Морды и хвосты унатхов закрывают одежду

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1338]
### Описание

Хвост (скр.1) и морда (скр.2) накладываются поверх одежды или вылезают за её пределы. Хорошо заметно на примере клоуна.

Возможно только в редакторе!

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/a4976453-e5b5-42c4-a9fb-438fe868d185)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/90f53352-54ce-41f3-af1e-75fbbf797cd8)

**Comment by Alwayswannahunt** [comment]
RobustToolbox moment
