### ISSUE TITLE
Сигнальная ракетница стреляет дробью

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1355]
### Описание

Оффы взяли и откатили довольно важную фичу ограничивающую стрельбу с сигнального пистолета только сигнальным патроном (фальшфейер).

[Оригинальная фича](https://github.com/space-wizards/space-station-14/pull/22349)
[Откат](https://github.com/space-wizards/space-station-14/pull/24679)
[Ишью оффов](https://github.com/space-wizards/space-station-14/issues/25289)

### Шаги воспроизведения

1. Выстрелить с сигнальной ракетницы любым патроном .50

**Comment by Ady4ik** [comment]
https://github.com/space-wizards/space-station-14/pull/33291

**Comment by Tris0r** [comment]
@stalengd Закрывай, неактуально.
