### ISSUE TITLE
Настройки громкости ттс не работают 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1365]
### Описание

Ползунки громкости ттс ничего не делают.

https://discord.com/channels/1097181193939730453/1262106716900823073/1262106716900823073

### Шаги воспроизведения

1. Зайти в настройки аудио на сервере 
2. Подергать ползунки

### Скриншоты

![image](https://github.com/user-attachments/assets/47fc60c9-fc11-4bd7-8b6c-165b1ab03bf7)

**Comment by Mishics** [comment]
Ау, когда решать проблему
