### ISSUE TITLE
Капюшон куртки из паутины

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1377]
### Описание

При изменение состояния капюшона (снять/надеть), спрайт с откинутым назад капюшоном остаётся и немного выделяется

https://discord.com/channels/1097181193939730453/1262863532807164088/1262863532807164088

### Шаги воспроизведения

1. Надеть/снять капюшон куртки из паутины -> 2. Осмотреть модельку куртки 

### Скриншоты

![image](https://github.com/user-attachments/assets/27d56772-1022-4070-b7a3-bfe029e49a20)
![image](https://github.com/user-attachments/assets/0b635471-0db4-4a01-8320-13bb0328f9c1)
![image](https://github.com/user-attachments/assets/b834314c-510b-4bda-96d2-218f9dea9892)
![image](https://github.com/user-attachments/assets/9a39c083-b7af-4533-997b-444fecb327e1)
![image](https://github.com/user-attachments/assets/e202da0c-774b-44d7-bcbf-8337ac8ff23a)

**Comment by Ady4ik** [comment]
Не воспроизводится. Спрайт капюшона отображается нормально.
