### ISSUE TITLE
Сломался поворот конструкций 

### ISSUE THREAD

**Issue by NightmareStalker** [SerbiaStrong-220/space-station-14#1380]
### Описание

Некоторые вещи при возведении поворачиваются в стандартное положение, не смотря на положение их призрака ранее. 
Например жалюзи, перила, лестницы/ступеньки. Может что-то еще.

### Шаги воспроизведения

1. Разместить призрак каких-то структур в любом из запад-север(юг?)-восток положении
2. Крафтим их
3. Увы...

### Скриншоты

https://github.com/user-attachments/assets/4e302cc8-d5cd-4329-97f4-123f58ca5fe3

**Comment by Mishics** [comment]
Так, приём-приём. Называю список того что не крутится - Все виды диванов, церковных скамеек, скамеек и барных диванов, все жалюзи, все виды ступенек (перила кажется оффы исправили) На этом кажется всё А ЕЩЁ ВЫ НЕ СКИНУЛИ СЮДА ССЫЛКУ НА ТРЕКЕР

https://discord.com/channels/1097181193939730453/1283399276088786997/1283399276088786997
