### ISSUE TITLE
Камера на уборочной машине ломается

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1382]
### Описание

Камера на уборочной машине ломается если будучи пристегнутым к ней кинуть предмет. 

### Шаги воспроизведения

1. Сесть на уборочную машину
2. Кинуть предмет 

### Скриншоты

![image](https://github.com/user-attachments/assets/b80709b7-439d-4d8f-b093-eec282edb165)

**Comment by Tris0r** [comment]
**Протестировал**
_Чтобы я ни кидал, как бы я ни кидал - воспроизвести баг не удалось._

**Comment by Ady4ik** [comment]
Отложено до повторного.
