### ISSUE TITLE
Стаминкрит колясочников

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1391]
### Описание

При получении стаминакрита ты можешь продолжить движение в любом направлении

https://discord.com/channels/1097181193939730453/1263477098958553170/1263554553815498873

### Шаги воспроизведения

Сесть на коляску, и пару раз стукнуть по себе батоном, и попытаться проехаться.

**Comment by ReeZer2** [comment]
Сейчас при получении стамин крита, колясочник отстегивается. Неактуально походу уже

**Comment by Tris0r** [comment]
**Протестировал.**

Сейчас при получении стамин крита колясочник отстёгивается.

**Comment by gogenych** [comment]
пофикшено
