### ISSUE TITLE
Камера ломается на т/с

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1392]
### Описание

Если слезть с коляски (ну или если тебя скинут), то при определённых действиях ломается фиксация камеры на пешке, и переносится на коляску. (примечание от ТС трекера: "Как я понял, так происходит из-за скрипта что вызывает тряску камеры, от броска предмета, взрыва, отключения гравитации и тому подобное что трясёт камеру")

https://discord.com/channels/1097181193939730453/1263477098958553170/1263477098958553170

### Шаги воспроизведения

 Взять колясочника, слезть с коляски, и кинуть её в сторону.

**Comment by OwlMe1steR** [comment]
### **Итоги**

Проверил все возможные варианты. Камера остаётся на кукле при любых манипуляциях с куклой на коляске.

**Comment by Ady4ik** [comment]
Отложено до повторного.
