### ISSUE TITLE
Проникновение переноской

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1396]
### Описание

Если кинуть переноской животных в маленькую дверь или стекло - она пролетит насквозь и перенесёт людей с собой.

https://discord.com/channels/1097181193939730453/1263476540117749760/1263476540117749760

### Шаги воспроизведения

1. Засунуть куклу в переноску -> 2. кинуть переноску в тонкое стекло/дверь

**Comment by Tris0r** [comment]
**Протестировал**
Баг работает немного по другому.
Переноску можно использовать и брать через стекла.

https://github.com/user-attachments/assets/013837b1-e5cc-4ac5-a5e8-a27f5bd9a8f2

**Comment by Tris0r** [comment]
Неактуально.
@stalengd закрывай
