### ISSUE TITLE
Переноски и ловушка

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1397]
### Описание

Если в переноску поместить кого/что-либо, а затем кинуть её в мусорку - существо не сможет выбраться и останется там до помощи другого игрока.

https://discord.com/channels/1097181193939730453/1263476540117749760/1263476540117749760

### Шаги воспроизведения

1. Поместить куклу в переноску -> 2. Закинуть в мусорку

**Comment by Tris0r** [comment]
**Протестировал**
Пока кукла находится в переноске и в мусорке при попытке выбраться будет появляться popup "Здесь слишком тесно".
