### ISSUE TITLE
Мессенджер 

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1398]
### Описание

Мессенджер уродлив, а так же механика написания другим людям, что не появились раунд стартом усложнена тем, что им в обязательном порядке надо зайти в мессенджер и только потом контакт появится в таблице.
Ушедшим в крио можно писать. Бывает, надо ждать чтобы сервера появились для КПК

https://discord.com/channels/1097181193939730453/1263467784986296401/1263467784986296401

### Шаги воспроизведения

1. Некст появиться на смене с другой куклой -> 2. Когда после старта появиться ещё кукла - увидеть что которая прилетела нет, а что с раундстарта - есть в списке.

**Comment by UnknownSS220** [comment]
Баг отсутствует, для игрока который прилетает на станцию требуется только при прибытии войти в месенджер, тоже самое с раундстарта, если с раундстарта кукла не зашла в месенджер его аккаунта не будет там если зашлато его аккаунт появится.

**Comment by Ady4ik** [comment]
Закрываю в соответствии с тем, что описано выше.
