### ISSUE TITLE
Крысиные слуги не атакуют зомби

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1403]
### Описание

Крысиные слуги не атакуют зомби. Даже когда их бьют, даже после приказа.

### Шаги воспроизведения

1. Быть королем крыс, нажать "атаковать" на зомби

**Comment by ReeZer2** [comment]
Баг не воспроизводится. Крысы атакуют зомби в любом лсучае, кроме крита.

**Comment by gogenych** [comment]
В таком случае закрываю
