### ISSUE TITLE
Музыка на экспедициях, в лобби

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1406]
### Описание

На экспедициях, когда начинает тикать двух минутный таймер, то всё ещё играет музыка болгарыча, вместо Квантума фит. Цвай. Также, в лобби порой почему то играет музыка взрыва ядерки Квантума фит. Цвай (Running in)

### Шаги воспроизведения

1. Дождаться финального таймера экспы/упадёт на рандом в лобби
2. Готово

**Comment by Bomjojuk** [comment]
Как только что оказалось, музыка выбирается тупо на рандом, но мне кажется, что так всё ещё не должно быть

**Comment by Kirus59** [comment]
Да, играет одна из этих
![Screenshot_20240721_005844_Chrome](https://github.com/user-attachments/assets/fdaf1ab3-1449-4859-a13a-ca9e3df3e650)

**Comment by Kirus59** [comment]
Running in играет только в лобби, а при ядерке играет Running out

**Comment by Bomjojuk** [comment]
В курсе, про неë и говорил

**Comment by Bomjojuk** [comment]
Если правильно всë помню, то по словам Цвая трек должен играть ТОЛЬКО на ядерке, а не в лобби
