### ISSUE TITLE
Перезарядка магазинов

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1424]
### Описание

Магазин(ы) лектера не перезаряжаются из коробки, а пули исчезают (возможно из-за рюкзака)

https://discord.com/channels/1097181193939730453/1264952031031066705

### Шаги воспроизведения

1. Начать перезарядку магазина коробкой с пулями

**Comment by ReeZer2** [comment]
Баг не воспроизводится, либо уже пофикшен

**Comment by gogenych** [comment]
Закрываеееем
