### ISSUE TITLE
Эмоции от шапок сломались

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1435]
### Описание

Плащ моли не дает эмоции моли, а должен. В трекере упоминаются еще ушки которые дают уву акцент, но они вроде только с щитспавна, на всякий случай тоже бы глянуть. 

https://discord.com/channels/1097181193939730453/1261354981668294717/1261354981668294717

### Шаги воспроизведения

1. надеть плащ моли
2. пожужжать

**Comment by Tris0r** [comment]
**Протестировал.**

Плащ моли и правда не даёт никакой эмоции, кроме крика ниана.
То же самое про кошачьи ушки - они не дают никаких эмоций, кроме крика фелинида.

**Comment by Kirus59** [comment]
Кажись нашел в чем проблема, при надевании такой одежды скорее всего не заменяется/ добавляются `allowedEmotes` в компоненте `SpeechComponent`
![Screenshot_20240911_125059_Chrome](https://github.com/user-attachments/assets/4f70b5a2-e625-4528-ad09-255547ce17a3)
