### ISSUE TITLE
Кнопка "осмотреть" не работает 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1439]
### Описание

UI кнопки "осмотреть" всплывает на секунду и пропадает 

https://discord.com/channels/1097181193939730453/1264328432364290129/1264328432364290129

### Шаги воспроизведения

1. Осмотреть что-то

### Скриншоты

![image](https://github.com/user-attachments/assets/0d8fec35-58b9-43ce-9372-ea2a21a57364)

**Comment by gogenych** [comment]
связано с #1253

**Comment by Tris0r** [comment]
неактуально.
