### ISSUE TITLE
Сломанный РИТЭГ излучает слишком много радиации

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1449]
### Описание

К сожалению используется для абуза энергии из воздуха
Необходимо:
- либо снизить количество радиации до минимальных значений
- либо убрать радиацию полностью
- либо сделать отдельный прототип ритэгов без радейки и попросить мапперов заменить их

Последний вариант наиболее предпочтительный.

https://discord.com/channels/1097181193939730453/1265620886015184979/1265633462396784641
https://discord.com/channels/1097181193939730453/1265299025398202418/1265299025398202418
https://discord.com/channels/1097181193939730453/1265322737547743282/1265322737547743282

**Comment by UrPrice** [comment]
Надо просто снизить количество радиации и дописать код, чтобы она была иссякаемой. Условно радиации там хватает на 10 минут пользования, дальше тащите новый ритег и снова ломайте. Желательно эти два показателя сделать зависимыми на прямой. Уровень радиации - время иссякания. Чем меньше времене тем ниже уровень радиации. Я уже давно думал так сделать, но скилишуе и впадлу не хотели.

**Comment by gogenych** [comment]
@Ady4ik закрепи его в ишуе, а то там уже мошна в дискорде

**Comment by ZoNeSRuS** [comment]
Когда я предлагал это понерфить то меня заклеймили пидарасом который опять пытается мешать инженерам играть.

**Comment by Ady4ik** [comment]
@ReeZer2 если будет не сложно - займись пожалуйста в ближайшее время.

**Comment by ReeZer2** [comment]
> @ReeZer2 если будет не сложно - займись пожалуйста в ближайшее время.

взял, забрал, скоро залью
