### ISSUE TITLE
Лодаут не работает с кожаной сумкой

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1477]
### Описание

Если выбрана кожаная сумка, лодаут не грузит безделушки в нее. Проблема заметна на авд

https://discord.com/channels/1097181193939730453/1266027878445744230/1266027878445744230

### Шаги воспроизведения

1. Выбрать кожаную сумку в лодаут
2. Выбрать безделушки
3. Заспавниться без безделушек

**Comment by Tris0r** [comment]
**Протестировал**

И правда, какую бы безделушку не выбрали - ни одна не спавнится.
