### ISSUE TITLE
Снятие с коляски должно занимать время.

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1478]
### Описание

Снятие куклы с коляски должно занимать секунд 5, это не так просто как кажется. Сейчас ты абсурдно делаешь это одним кликом, тем самым полностью лишаешь человека способа передвижения.

Насколько знаю подобная система уже реализована для машины уборщика

**Comment by Ady4ik** [comment]
Решение вопроса со складыванием коляски и всех остальных предметов с компонентом Foldable будет в другом ПРе
