### ISSUE TITLE
Скрытая камера дека

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1490]
### Описание

Скрытая камера не снимается с предметов (примечание автора: возможно дело в том что камера у меня была выключена и не настроена, а еще если вы меня отправите писать оффам я взорвусь)

### Шаги воспроизведения

\гайд от автора\ Установить скрытую камеру (у меня она была выключена и не настроена) -> шифт лкм по объекту ->пкм по месту где была установлена камера -> попытаться нажать на кнопку "убрать камеру"

**Comment by OwlMe1steR** [comment]
### **Итоги**

Недостаточно информации, всё открепляется. 
Единственное место, где скрытая камера остаётся прикреплённой - это лампы. И то, она там держится только потому, что не была настроена.

За шаги воспроизведения вообще руки бы оторвал: куда, кому, как устанавливал - неизвестно.

**Comment by Ady4ik** [comment]
Закрыто до повторного.
