### ISSUE TITLE
термические очки

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1495]
### Описание

Терм. очки и имплант некорректно работают - по логике они должны просвечивать ТЁПЛЫХ существ, но на деле - просвечивают трупы, слаймов, пИИ, (роботов?). А тёплые предметы не отображает - например: гиропрот/автолат, печи, еду, горячие напитки и канистры и тп. Так же было бы хорошей идеей меня цвет экрана при ношении очков.

### Шаги воспроизведения

1. Надеть терм очки -> 2. Смотреть на все перечисленные вещи

**Comment by gogenych** [comment]
закрываю т.к. частично копирует  #1466
