### ISSUE TITLE
Баллоны не открываются

### ISSUE THREAD

**Issue by NightmareStalker** [SerbiaStrong-220/space-station-14#1506]
### Описание

Баллон не открывается в руке через Alt+ЛКМ. Звук открытия есть - по факту не открывается. 
Нужно класть на пол и открывать, чтобы спустить набранный газ, отчего баллон улетает, и чтобы закрыть - тоже на полу.

### Шаги воспроизведения

1. Взять в руку баллон любого газа
2. Навестись мышью. Попробовать открыть через Alt+ЛКМ
3. Услышать звук открытия/закрытия - обнаружить, что ни разу не работает

### Скриншоты

https://github.com/user-attachments/assets/97fb5404-85db-4089-988d-a42c8d4e8d88

**Comment by ReeZer2** [comment]
Не воспроизводится
