### ISSUE TITLE
Поправить описание набора связиста

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1510]
### Описание

У "Набора связиста" вора неактуальное описание. Необходимо убрать "портативный монитор экипажа"

https://discord.com/channels/1097181193939730453/1181358173492346880/1269526428505079878

### Скриншоты

![image](https://github.com/user-attachments/assets/7aa2ff66-855e-49d7-bc6c-c9bc0b55e950)
![image](https://github.com/user-attachments/assets/6862aecc-8d0f-44b9-9286-3bae6bd6fa92)
![image](https://github.com/user-attachments/assets/163a1572-cc1c-4b97-bee7-44025dc2429d)

**Comment by VuykoSheshych** [comment]
Сделаю.

**Comment by VuykoSheshych** [comment]
Короче, там в 46-ой строке в файле space-station-14\Resources\Locale\ru-RU\thief\backpack.ftl нужно удалить "портативный монитор экипажа" для решения. А у меня руки стали кривые - я не могу нормально PR сделать со второй попытки...

**Comment by Ady4ik** [comment]
Сделаю
