### ISSUE TITLE
Пробник ТТС в персонализации не работает 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1515]
### Описание

ТТС в персонализации персонажа не проигрывается. 

https://discord.com/channels/1097181193939730453/1269758291454595253/1269758291454595253

### Шаги воспроизведения

1. Персонализировать персонажа
2. Проиграть любой голос

### Скриншоты

![image](https://github.com/user-attachments/assets/6642c55c-fdd4-4380-9dcb-2b2e374bcd82)

**Comment by Tris0r** [comment]
**Протестировал.**

Скорее всего в то время лаганул сам ТТС. Сейчас проблемы я не обнаружил, всё прекрасно работает.
