### ISSUE TITLE
Говорящие фигурки молчат

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1516]
### Описание

Функционал мини-фигуркам членов экипажа добавленный оффами в https://github.com/space-wizards/space-station-14/pull/30455 у нас не работает. Использование проходит, но фраза не говорится

### Шаги воспроизведения

1. Взять фигурку в руки
2. Прожать использование в руке и наблюдать отсутствие фразы

### Скриншоты

![изображение_2024-08-05_011431822](https://github.com/user-attachments/assets/21a26608-9920-4c2f-bd79-d28456ea23cb)

**Comment by Kirus59** [comment]
Вероятно не работает из-за того, что у нас нельзя писать фразы в чат на инглише.
Нужно либо самостоятельно перевести все эти фразы, либо дождаться локализации от корвакса.

**Comment by Kirus59** [comment]
А у Корвакса еще даже апстрима с этим ПРом не было, увы

**Comment by Bomjojuk** [comment]
Видимо тогда поэтому

**Comment by Ady4ik** [comment]
Сделаю
