### ISSUE TITLE
Вернуть химку

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1545]
### Описание

С апстримом в - все кувшины изменили имя на дубликаты, а мензурки снова можно перелить только на 50u.

https://discord.com/channels/1097181193939730453/1270774549721645147
https://discord.com/channels/1097181193939730453/1270782954762928179

### Шаги воспроизведения

1. Посмотреть в ХимкоМат -> 2. Взять кувшин и ПКМ по нему ->3. Выбрать "перемещаемое количество"

### Скриншоты

![image](https://github.com/user-attachments/assets/80c0e98f-8f2b-4dc4-86f9-a61de5776cff)
![image](https://github.com/user-attachments/assets/8e85077d-91ca-4025-a275-d5e3b3954c27)

**Comment by Tris0r** [comment]
**Протестировал**
Уже неактуально. Пофиксили.

**Comment by Bomjojuk** [comment]
Актуально, но частично. Сейчас всё ещё нет варианта больше 50-ти юнитов на железных канистрах зеленых

**Comment by Tris0r** [comment]
Но канистры и не относятся к меду
