### ISSUE TITLE
Аварийные наборы

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1546]
### Описание

С недавней обновой у многих из сумок исчезают их аварийные наборы (непонятно почему)

https://discord.com/channels/1097181193939730453/1270764060266463315

### Шаги воспроизведения

1. Появиться некстом/после начала смены -> 2. Открыть сумку

**Comment by Alwayswannahunt** [comment]
После общения с игроками и нескольких примеров было выявлено, что проблема точно происходит с рюкзаком грузчиком и при наличии предметов в лодауте.

Из личного опыта: набрать много херни в лодауте, выбрать сумку -> заспавнится в крио -> не найти лодаут ни под собой, ни в рюкзаке -> побегать нное время и вернутся на место спавна -> обнаружить свою аварийку.
В терминале происходило примерно также, но вроде я находил аварийку под собой чуть раньше

**Comment by gogenych** [comment]
нужно больше информации (c) reezii

**Comment by EstKemran** [comment]
https://discord.com/channels/1158128815311171638/1290030517055520879/1290069773270388736

Не актуально

**Comment by Ady4ik** [comment]
Закрою с возможностью реопена.
Пока что сделаем вид, что отложено.
