### ISSUE TITLE
Заказы карго

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1548]
### Описание

Заказы в карго (их покупки и названия) сломались

### Шаги воспроизведения

1. Открыть консоль/планшет заказов. -> 2. Оформить заказ и купить что-либо

### Скриншоты

![image](https://github.com/user-attachments/assets/7d1398b5-de95-4246-9f85-d5bc0f02c93b)

**Comment by Kirus59** [comment]
Исправлено тут https://github.com/SerbiaStrong-220/space-station-14/pull/1537
