### ISSUE TITLE
ранец борга шахтёра

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1549]
### Описание

При полном израсходовании реактивного ранца в модуле "с Кинетическим ускорителем" он не собирается заполняться повторно и активироваться даже если его и накачать газом

https://discord.com/channels/1097181193939730453/1269668581579296828

### Шаги воспроизведения

1. выпустить весь газ из ранца -> 2. Заполнить ранец из канистры -> 3. пытаться полетать

**Comment by Tris0r** [comment]
**Протестировал**
Уже неактуально. Ранец пополняется сам.
