### ISSUE TITLE
UI крафта

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1551]
### Описание

Если попытаться открыть меню крафта с занятыми руками (обеими) - он не откроется

### Шаги воспроизведения

1. заполнить слоты рук -> 2. тыкать на G

**Comment by ReeZer2** [comment]
![image](https://github.com/user-attachments/assets/cfec2d2a-c3ba-44e9-a68e-6bf1beb751af)
![image](https://github.com/user-attachments/assets/3e83a6ab-dfb4-41d7-889d-507e6aac3556)

Не воспроизводится

**Comment by gogenych** [comment]
не воспроизводится
