### ISSUE TITLE
Намордник не работает

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1555]
### Описание

Намордник даёт право тебе говорить и никак не мешает речи.

### Шаги воспроизведения

1. Надеть на себя намордник
2. Попытаться что-то  сказать

### Скриншоты

![image](https://github.com/user-attachments/assets/40dc1218-a5e4-4bba-8845-81ae95ffab1b)

**Comment by Kirus59** [comment]
Неактуально
![image](https://github.com/user-attachments/assets/b6bb6f14-2c76-4be2-a536-5e16cc9a62fe)
