### ISSUE TITLE
Щит снова может быть нулевым (агентом?)

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1564]
### Описание

У синего щита видимо снова слетел "имунн" к антагонистам. Необходимо тестить, так как лично наблюдалось лишь единоразово. 
Прикрепляю скриншот (на той смене человек был изначально синим щитом) 

### Шаги воспроизведения

1. Быть ОСЩ
2. Дождаться выпадения антагов
3. Наблюдаем?

### Скриншоты

![image](https://github.com/user-attachments/assets/8e707e77-90e3-4a2d-b1c4-283044e2d5ab)

**Comment by Ady4ik** [comment]
Инфа по ишуе собирается.
Просьба временно не брать в работу.

**Comment by Ady4ik** [comment]
ОСЩ стал зомби после укуса другим нуликом. 
Проблем не вижу.

**Comment by Bomjojuk** [comment]
> ОСЩ стал зомби после укуса другим нуликом. Проблем не вижу.

А почему он тогда отображался как нулевой в результатах раунда?...
