### ISSUE TITLE
Спам объявлением войны

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1565]
### Описание

На данный момент можно спамить объявлением войны соответствующим пультом

### Шаги воспроизведения

1. Очень быстро прожимать кнопку объявления войны

### Скриншоты

Трекер с демонстрацией бага: https://discord.com/channels/1097181193939730453/1271093400044703884/1271093400044703884

**Comment by OwlMe1steR** [comment]
### **Итоги**

Что на Лонопере, что на пресете Нукеров. 
При объявлении войны, как бы я ни старался, больше двух раз проспамить сообщение не получается. Подозреваю, что с автокликером можно проспамить и больше.

Главное, что ТК не дюпаются.

**Comment by ReeZer2** [comment]
![image](https://github.com/user-attachments/assets/0bd9b64d-cc83-4970-8be2-623f9a1f5fce)
Всё так же работает
