### ISSUE TITLE
Пропажа одежды 

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1568]
### Описание

В начале раунда попали все вещи при перезаходе, не смог подбирать вещи.  Другие люди сообщали что у них такое было из-за высокого пинга.

### Шаги воспроизведения

-

**Comment by Tris0r** [comment]
![image](https://github.com/user-attachments/assets/9bcb54d8-9875-48ae-a2aa-f83b542d1851)
Закрыто.
