### ISSUE TITLE
Невидимость Ниндзя

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1575]
### Описание

После апстрима слетел наша невидимость ниндзя и был заменен на тот, что в оффициальном билде

Ссылка на соответствующий трекер: https://discord.com/channels/1097181193939730453/1272490795714347080/1272490795714347080

### Шаги воспроизведения

1. Быть ниндзя
2. Включить маскирующий покров
3. Наблюдаем

### Скриншоты

Первый скрин - сейчашний инвиз (оффов)
второй - наш изначальный

![image](https://github.com/user-attachments/assets/5bb53e5e-7cd2-48f1-9e91-63a2318d9c26)
![image](https://github.com/user-attachments/assets/e7b609b0-ddf7-470c-b4e6-d36e0dc0afe1)

**Comment by Ady4ik** [comment]
@gogenych дубликат #1501 ?

**Comment by gogenych** [comment]
> @gogenych дубликат #1501 ?

нет
