### ISSUE TITLE
Агент без часов

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1583]
### Описание

Поздним подключением может выдать агента независимо от стоящей галочки

### Шаги воспроизведения

1. Не ставить галочку на агента
2. Зайти после начала раунда (и скорее всего после 7-10 минут)

**Comment by OwlMe1steR** [comment]
### **Итог**

Создал локальный сервер и зашёл с 6 аккаунтов. 
Активировал пресет Traitor и добавил gamerule на спящих агентов.
Из всех 6 персонажей никто не получил роль антагониста, даже те, у кого стояли соответствующие галочки.

Баг не воспроизвёлся. 
Нужно проверить, что происходило в раунде и как антаг роль была выдана человеку, у которого не стояла галочка.

**Comment by gogenych** [comment]
![image](https://github.com/user-attachments/assets/488199a4-cc11-476d-96c6-b0e56031c507)

**Comment by Kirus59** [comment]
> ### **Итог**
> Создал локальный сервер и зашёл с 6 аккаунтов. Активировал пресет Traitor и добавил gamerule на спящих агентов. Из всех 6 персонажей никто не получил роль антагониста, даже те, у кого стояли соответствующие галочки.
> 
> Баг не воспроизвёлся. Нужно проверить, что происходило в раунде и как антаг роль была выдана человеку, у которого не стояла галочка.

@OwlMe1steR 
Ты во время тестов не менял `playerRatio:` в прототипе геймрула `Traitor`?
![image](https://github.com/user-attachments/assets/54d9ce78-b53e-4e55-8e2f-a059249acfa3)

Если нет то и не выпадет, ибо 1 роль трейтора дается на каждые 10 человек, а ты чекал лишь при 6 акках.

**Comment by Kirus59** [comment]
@gogenych Вероятнее всего не баг, ибо у нас на некоторые роли вообще не настроено ограничение по часам.
Вот скрин с нулевого акка на локалке.
![image](https://github.com/user-attachments/assets/fec8923c-dcfe-476b-a4ac-48b8ea385cd8)
