### ISSUE TITLE
Цели у подкреплений агентов

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1593]
### Описание

На данный момент у подкрепления агентов присутствуют свои личные цели на выполнение. Сломалось, судя по всему, из-за новой системы выбора "подкласса" подкрепления

Ишуе по данному трекеру: https://discord.com/channels/1097181193939730453/1273046582446653500

### Шаги воспроизведения

1. Купить маяк подкрепления агента
2. Ждем пока гост возьмет роль
3. Смотрим за подкрепление свои цели

**Comment by UnknownSS220** [comment]
баг воспросизводится, у подкрепления свои цели.
