### ISSUE TITLE
Майндслейв записывается как дракон/нинзя

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1594]
### Описание

На данный момент если в раунде был геймрул слипер Агентов, ниндзи/дракона и слипер использовал на ком то имплант подчинения разума, то подчиненный разум будет записываться в гринтексте как второй нинзя/дракон.

### Шаги воспроизведения

1. Зафорсить геймрулы слиперов и ниндзи
2. Сделать любую куклу (с душой) подчиненным разумом
3. Оканчиваем раунд и наблюдаем баг в гринтексте

### Скриншоты

![image](https://github.com/user-attachments/assets/c7da6de0-c66e-46c0-a369-198e8e57456b)

**Comment by UnknownSS220** [comment]
баг воспроизвести не удалось, гринтекст работает исправно.
