### ISSUE TITLE
Таймер-Сигнала

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1634]
### Описание

Нельзя разобрать/сломать таймер сигнала

https://discord.com/channels/1097181193939730453/1275782956245323807/1275782956245323807

### Шаги воспроизведения

1. Построить/поставить таймер сигнала -> 2. Пытаться сломать/разобрать его

**Comment by Oxygen033** [comment]
На локалке не воспроизводится и при постройке и при размещении
![image](https://github.com/user-attachments/assets/245add4f-4d50-4c6c-bb73-bd9006563588)

**Comment by Ady4ik** [comment]
Не воспроизводится. При повторном возникновении переоткрыть ишуе. Автор ишуе уведомлен - весь фидбек внутрь трекера.
