### ISSUE TITLE
Жнец и взрывы

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1656]
### Описание

Когда жнец находится в астрале он может быть убит с помощью какого-либо взрыва

### Шаги воспроизведения

1. Заспавнить жнеца
2.Сделать взрыв на том же тайле

**Comment by Bomjojuk** [comment]
По сути ишуй связан с этим: https://github.com/SerbiaStrong-220/space-station-14/issues/1572
