### ISSUE TITLE
Постоянный звук двойного лазерного меча

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1661]
### Описание

На данный момент если заспамить включение/выключение двойного лазерного меча, велик шанс того, что звук "жужжания" меча зациклиться и будет воспроизводиться даже в выключенном состоянии

Трекер по багу: https://discord.com/channels/1097181193939730453/1276845293220134932

### Шаги воспроизведения

1. Быстро и постоянно прожимать переключение двойного меча (Повторять до получения результата)
2. Наблюдаем баг

**Comment by Ady4ik** [comment]
Неактуально
