### ISSUE TITLE
При включенных магнитках в космосе нельзя включить джетпак

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1685]
### Описание

На данный момент если кукла находиться в космосе но на ней есть включенные магнитные боты, то джетпак невозможно включить.

Трекер по багу: https://discord.com/channels/1097181193939730453/1278706113331859456/1278706113331859456

### Шаги воспроизведения

1. Надеть магнитные ботинки и включить их
2. Выйти с грида в космическое пространство 
3. Попытаться включить джетпак
4. Наблюдаем

**Comment by Tris0r** [comment]
**Протестировано**
Джетпак НЕ включается, если включены магнитки.
