### ISSUE TITLE
Отпечатки при снятии вещи с куклы

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1694]
### Описание

На данный момент если снять вещь с куклы через меню экипировки (на кнопку е или перетаскивание куклы на себя), то "ворующая" кукла не оставит следов (отпечатки, волокна)

### Шаги воспроизведения

1. Открыть меню экипировки другой куклы на е
2. Снять любую вещь с неё
3. Проверяем на наличие следов сканером
4. Наблюдаем отсутствие своих следов

### Скриншоты

![image](https://github.com/user-attachments/assets/f780dfea-3614-44fb-bc0e-f7522b095bb5)
![image](https://github.com/user-attachments/assets/8dea751f-3e4b-4f9b-9ca9-66a82c53b685)

**Comment by Kirus59** [comment]
Фиксится оффами

**Comment by Bomjojuk** [comment]
Ну короче там оффы пофиксили
