### ISSUE TITLE
Убийство хозяина за голоклоуна

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1700]
### Описание

На данный момент голоклоун наносит урон своему владельцу взрывом оружия при стрельбе из-за своего "гена" неуклюжести.

### Шаги воспроизведения

1. Стать голоклоуном
2. Пострелять с любого огнестрельного оружия (желательно скорострельного, для более заметного эффекта)
3. Наблюдаем урон по аое, в том числе по своему хосту

**Comment by Mishics** [comment]
А баг то где? Клоун наносит себе урон - да. Хозяину урон  переходит? Да.

**Comment by Kirus59** [comment]
Тоже не понимаю где баг, голоклоун (как и голопаразит) передаёт весь урон с себя владельцу.
Если ты имеешь ввиду дублирование дамага (типо и с голоклоуна и из-за сплэша) то опять же а почему его не должно быть?

**Comment by Bomjojuk** [comment]
> Тоже не понимаю где баг, голоклоун (как и голопаразит) передаёт весь урон с себя владельцу. Если ты имеешь ввиду дублирование дамага (типо и с голоклоуна и из-за сплэша) то опять же а почему его не должно быть?

Кирус, голо сейчас пропускает всë через себя :okayge:, насколько помню

**Comment by Kirus59** [comment]
> Кирус, голо сейчас пропускает всë через себя :okayge:, насколько помню

Он пропускает только огнестрел, с лазера, в мили, взрывами все прекрасно дамажится и передаётся владельцу

https://github.com/user-attachments/assets/ef581226-743f-455c-aa82-3379f720dee9

**Comment by Bomjojuk** [comment]
> > Кирус, голо сейчас пропускает всë через себя :okayge:, насколько помню
> 
> Он пропускает только проджектайлы. Хитсканом, в мили, взрывами все прекрасно дамажится и передаётся владельцу
> 
>  2024-08-31.13-54-56.mp4

Ну тогда я акробаст и пивной барон
