### ISSUE TITLE
Прибор для электролиза не работает нормально с большими контейнерами

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1719]
### Описание

На данный момент прибор для электролиза нормально не воспринимает хранилища жидкостей объёмом больше 100u, и при загрузке контейнера с жидкостью, объем которой превышает 100u на выходе вся жидкость "выше" удаляется

Трекер по багу: https://discord.com/channels/1097181193939730453/1279745607237636098/1279745607237636098

### Скриншоты

1. Поставить в прибор, например, бс мензурку с 1000u воды
2.  Запускаем процесс
3. Получаем на выходе 100u обработанного вещества

**Comment by Tris0r** [comment]
**Протестировал**
Баг не воспроизводится. Всё работает как надо.

**Comment by Ady4ik** [comment]
Все работает нормально.
