### ISSUE TITLE
Нулевой спавн руды на лавовых планетах

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1722]
### Описание

На данной момент на любой экспедиции на лавовую планету НЕ спавниться руда в принципе

### Шаги воспроизведения

1. Выбрать экспедицию на лавовую планету
2. Начинаем копать/просто пользуемся фуллбрайтом
3. Наблюдаем полное отсутствие руды и комплекса на планете

### Скриншоты

![image](https://github.com/user-attachments/assets/5abab8d7-30c1-4aa9-8367-ddef349d933a)

**Comment by Tris0r** [comment]
**Протестировал**
Всё так, как и описано. Руда НЕ спавнится на лавовых планетах ВООБЩЕ.
