### ISSUE TITLE
Бумажные двери

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1726]
### Описание

При открывании бумажная дверь издаёт каменный скрежет при открывании.

### Шаги воспроизведения

1. Построить дверь из бумаги -> 2. Включить музон погромче

**Comment by gogenych** [comment]
отдал прототиперам

**Comment by chell4592** [comment]
исправил: https://github.com/SerbiaStrong-220/space-station-14/pull/1735#issue-2502078906
если нужно было в описании ПРа приложить ссылку на ишуе - пните плз, в дискорде мне не ответили
