### ISSUE TITLE
Банджо нельзя носить на спине

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1728]
### Описание

Банджо нельзя повесить на слот спины

### Шаги воспроизведения

1.  Попробовать повесить банджо на спину

**Comment by gogenych** [comment]
отдал прототиперам

**Comment by Ady4ik** [comment]
https://discord.com/channels/1158128815311171638/1285618385434054697
Ожидаем спрайт
