### ISSUE TITLE
юбка и комбез СБ не отображаются в руках

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1729]
### Описание

Собственно юбка и комбез в руках отображаются как "проклятье 220". Скорее всего проёбан путь к файлу текстуры

### Шаги воспроизведения

1. взять в руку комбез или юбку сб

**Comment by gogenych** [comment]
![image](https://github.com/user-attachments/assets/4fffbec6-a8f0-4122-9b83-011fea565c9e)
![image](https://github.com/user-attachments/assets/e9bdfd89-ffcc-42c2-90be-c666c3b942a9)

**Comment by Tris0r** [comment]
**Протестировал**
"проклятье 220" отображается только если взять в руку юбку-комбинезон СБ.
![image](https://github.com/user-attachments/assets/74951132-b554-478e-9422-eb3e299e1c1c)
