### ISSUE TITLE
Коробка для патрон и патронташ заряжают без кд

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1736]
### Описание

В патронташ и коробки для патрон должны заряжать с той же скоростью, что и руками, но фактически делают это без каста

### Шаги воспроизведения

1. Зарядить дробовик или обойму коробкой патрон или патронташем

**Comment by Tris0r** [comment]
**Протестировано**
Баг не воспроизводится. Всё заряжается с одной скоростью.

**Comment by Ady4ik** [comment]
Неактуально.
