### ISSUE TITLE
admin observe не работает

### ISSUE THREAD

**Issue by Ady4ik** [SerbiaStrong-220/space-station-14#1747]
### Описание

При выборе наблюдать через admin observe не выдается aghost. Необходимо дополнительно прописывать команду в консоль.

### Шаги воспроизведения

1. Зайти в лобби
2. Нажать Наблюдать
3. Нажать admin observe
4. Получить обычного госта, вместо агоста.

**Comment by Kirus59** [comment]
Там прикол в том, что при выборе player observe автоматически прописывается `deadmin`.
Считаешь что все же стоит для `admin observe` добавить заход в агоста сразу?

**Comment by Ady4ik** [comment]
@Kirus59 при заходе в admin observe не выдается. При заходе в player observe все нормально.

**Comment by Tris0r** [comment]
Так это же не баг, а фича.
