### ISSUE TITLE
Магнитные ботинки синдиката не работают как баллон для дыхания

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1753]
### Описание

Нв данный момент кроваво-красные ботинки синдиката не работают как баллон для дыхания, не смотря на наличие соответствующей кнопки действия.

Трекер по багу: https://discord.com/channels/1097181193939730453/1281185921902837790/1281185921902837790

### Шаги воспроизведения

1. Надеть синди-боты
2. Имея на лице любую дыхательную маску попытаться подать воздух по кнопке
3. Наблюдаем отсутвие эффекта

**Comment by Tris0r** [comment]
**Протестировал**
Если пытаться активировать подачу воздуха через меню действий, то включается режим магнитных ботинок.
Переключение воздуха через интерфейс магниток - работает, так же как и "Переключить баллон" тоже работает.
