### ISSUE TITLE
Магнитные ботинки 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1759]
### Описание

Не получается подключить через кнопку действия магбутсы как баллон и дышать через них 

https://discord.com/channels/1097181193939730453/1281185921902837790/1281185921902837790

### Шаги воспроизведения

1. При нажатии на кнопку действия подключения магбутс, они должны подключаться  как баллон.

**Comment by gogenych** [comment]
Обязательно потестить на билде оффов!

**Comment by stalengd** [comment]
На билде оффов тоже обнаружен
![image](https://github.com/user-attachments/assets/17c21599-d7a9-418e-8657-2676834f657b)

**Comment by stalengd** [comment]
Быстрая инспекция кода показала что баг несложный, думаю можно поручить и новичку, но тут работа с кодом

**Comment by Tris0r** [comment]
https://github.com/SerbiaStrong-220/space-station-14/issues/1753
