### ISSUE TITLE
Малая победа синдиката

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1773]
### Описание

На данный момент в гринтекст засчитывает малую победу синдиката при соло яо, даже если капитан эвакуировался с диском.

![image](https://github.com/user-attachments/assets/f8aa857f-9640-47e0-8131-d86afa8c1f20)

### Шаги воспроизведения

1. Ликвидировать соло яо и эвакуироваться как капитан (для удобства) с диском при себе
2. Читаем гринтекст
3. Наблюдаем неправильное засчитывание победы синдиката

**Comment by Tris0r** [comment]
ЯО же ликвидирован уже.

**Comment by UnknownSS220** [comment]
соло нюкера нету так что учтём этот баг когда главы захотят вернуть его назад.
