### ISSUE TITLE
Неправильное положение клоунского молотка при широком ударе

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1774]
### Описание

На данный момент при широком ударе клоунского молотка его спрайт неправильно отображается, скриншот прилагается.

### Шаги воспроизведения

1. Взять в руки клоунский молоток и ударить широким ударом
2. Наблюдаем неправильное положение спрайта

### Скриншоты

![image](https://github.com/user-attachments/assets/cecfdd5b-d8e4-4e21-bb97-fffe968c1949)

**Comment by Tris0r** [comment]
**Протестировано**
Баг воспроизводится. Закину к прототиперам.
