### ISSUE TITLE
Не работает интерфейс консоли криминальных записей

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1790]
### Описание

У консоли криминальных не работает корректно интерфейс. Буквально пустой интерфейс

### Шаги воспроизведения

1. Открыть консоль криминальных записей

### Скриншоты

![image](https://github.com/user-attachments/assets/adbb6ebc-bd30-4393-bbdb-940745846d3b)

**Comment by ReeZer2** [comment]
https://github.com/SerbiaStrong-220/space-station-14/pull/1784

**Comment by ReeZer2** [comment]
ПОФИКШЕНО, ЗАКРЫВАЕМ
