### ISSUE TITLE
термальные очки не работают 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1791]
### Описание

Не видно существ сквозь стены.

Ждем пару дней пока не деплойнут новый апстрим и потом тестим!
https://discord.com/channels/1097181193939730453/1282011440504377438/1282011440504377438

### Шаги воспроизведения

1. Надеть очки

**Comment by Tris0r** [comment]
Неактуально.
Сейчас они работают.
