### ISSUE TITLE
Сломанный ui автомата "космический злодей"

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1792]
### Описание

На данный момент у аркадного автомата "космически злодей" полностью сломан ui, который не выводит цифры урона, хп и тд.

### Шаги воспроизведения

1. Открыть интерфейс аркадного автомата
2. Наблюдаем неработающую игру

### Скриншоты

![image](https://github.com/user-attachments/assets/c05865bc-d4b1-48d4-8420-f8d11ad10a41)

**Comment by gogenych** [comment]
Баг воспроизводится. Интерфейс не работает

**Comment by Ady4ik** [comment]
![image](https://github.com/user-attachments/assets/35df320d-f2aa-4339-9760-744e94e2d529)
Неактуально
