### ISSUE TITLE
Невозможность сохранить изменение настройки ухода в крио при ссд

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1793]
### Описание

На данный момент при изменении настройки ухода в крио при длительном ссд не позволяет сохранять настройки персонажа (кнопка остается некликабельной)

### Шаги воспроизведения

1. Открыть редактор персонажа
2. Изменить настройку ухода в крио на другое состояние
3. Наблюдаем отсутствие интерактивности у кнопки сохранения

### Скриншоты

![image](https://github.com/user-attachments/assets/70433ddd-9ecb-4d10-b819-e8d8918041b0)

**Comment by ReeZer2** [comment]
https://github.com/SerbiaStrong-220/space-station-14/issues/1240
