### ISSUE TITLE
Полеты на вантузе

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1794]
### Описание

На данный момент можно достичь бесконечного полета с помощью смазанного смазкой вантуза и уронив его

трекер по багу: https://discord.com/channels/1097181193939730453/1281322632980992083

### Шаги воспроизведения

Указаны в видео: https://cdn.discordapp.com/attachments/1281322632980992083/1281325736522678352/Desktop_2024.09.05_-_21.49.34.08.mp4?ex=66dd4955&is=66dbf7d5&hm=f1f5ac7cc99647e1d85cf5e462d9e38e6a6de6dc86c2de8deb4c22dce8580442&

**Comment by Tris0r** [comment]
**ПРОТЕСТИРОВАЛ**
Баг воспроизводится

**Comment by ReeZer2** [comment]
Баг до сих пор существует

**Comment by Tris0r** [comment]
По состоянию на 11 декабря 2024 года - баг работает до сих пор.
