### ISSUE TITLE
При перезаходе спавняться окна без интеракции

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1798]
### Описание

На данный момент при отключении от сервера с открытым окном интерфейса (кпк, часы) и последующим подключением обратно появляется дополнительное окно интерфейса без каких-либо интерактивных элементов (часы не идут, кпк не кликабелен)

### Шаги воспроизведения

1. Открыть окно интерфейса (часы, кпк)
2. Отключаемся от сервера
3. Переподключаемся
4. Наблюдаем статичное окно

**Comment by Tris0r** [comment]
**Баг не воспроизводится**
