### ISSUE TITLE
Отсутствие резиновых боеприпасов в крафте

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1799]
### Описание

На данный момент в игре нет никакого способа распечатать резиновые боеприпасы кроме раундстарт боеприпасов 

### Шаги воспроизведения

1. Открывает интерфейс Охранного техфаба/фаба патронов
2. Ищем резиновые боеприпасы
3. Наблюдаем отсутствие возможности изготовления резиновых боеприпасов 

### Скриншоты

![image](https://github.com/user-attachments/assets/65afe8cd-1e33-4eb9-a50c-8ad38087455c)

**Comment by Tris0r** [comment]
**Протестировал**
И правда, резиновые патроны никак не скрафтить.
