### ISSUE TITLE
У зомби не зомби-кровь

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1827]
### Описание

На данный момент при заборе крови из зомби напрямую или из луж крови раненных зомби мы получаем почти полностью только обычную кровь (кровь зомби присутствует, но в крайне небольшом количестве). Как понял, изначально у зомби вся кровь - обычная, но та кровь, что восстанавливается со временем уже является зомби-кровью.

Протестировал: Шприцом опустил уровень крови зомби до нуля, далее через некоторое время набрал кровь снова и уже тогда вся кровь была кровью зомби

### Шаги воспроизведения

1. Набираем напрямую из зомби кровь в щприц
2. Наблюдаем в шприце обычную кровь вместо крови зомби

**Comment by Tris0r** [comment]
Я тоже протестил и бомжежук говорит правду.
Если взять кровь у зомби сразу, то в шприце будет всего ~7% крови зомби, а остальное - обычная кровь.
