### ISSUE TITLE
Шаттл гибает гораздо дальше чем сам шаттл

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1851]
### Описание

Зона гиба от шаттла гораздо больше чем сам шаттл

### Шаги воспроизведения

1. Отойти где-то на 5 тайлов от примерной зоны прибытия шаттла
2.  Ожидать прибытия шаттла

### Скриншоты

![image](https://github.com/user-attachments/assets/c6e7393c-0ddd-4ada-afa3-461ceba5c4ad)

**Comment by OwlMe1steR** [comment]
**Итоги**

Проверил на всех картах. Достаточно всего одного тайла между местом прибытия и куклой, чтобы не умереть. 
Всё работает корректно. Недостаточно данных для воспроизведения бага.

**Comment by Ady4ik** [comment]
Недостаточно данных для решения бага.
