### ISSUE TITLE
Размер феленидов не отображается в редакторе персонажа

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1859]
### Описание

На данный момент в редакторе персонажа полностью отсутствует скалирование куклы с расой феленида, в результате чего кукла выглядит просто как человек стандартного размера 

### Шаги воспроизведения

1. Создать/открыть редактуру персонажа-феленида
2. Наблюдаем отсутствие скалирования (скриншот ниже)

### Скриншоты

![image](https://github.com/user-attachments/assets/07ec1b6c-88f8-478a-bae6-4a4abd9a3e4e)

**Comment by gogenych** [comment]
ну это, так сказать, не в приоритете :D

**Comment by gogenych** [comment]
> ну это, так сказать, не большая проблема :D

**Comment by lzk228** [comment]
лёгкий фикс, добавьте скейл для dummy фелинида

**Comment by OwlMe1steR** [comment]
Удалены, неактуально

**Comment by Ady4ik** [comment]
Закрыто, будет решено с рефактором фелинидов.
