### ISSUE TITLE
Шляпа дриллсержанта находиться в лодауте находиться в настройке плеча

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1885]
### Описание

На данный момент шляпа дриллсержанта в настройке лодаута находиться не в том слоте, необходимо перенести в настройку головного убора.
Ишуе по трекеру: https://discord.com/channels/1097181193939730453/1285961761417334855

### Шаги воспроизведения

1. открыть лодаут офицера сб
2. Открываем вкладку шеи
3. Наблюдаем шляпу в настройке нешляп

### Скриншоты
![image](https://github.com/user-attachments/assets/871c0c8b-ee3e-4f4a-b863-d43c450882fb)

_No response_

**Comment by chell4592** [comment]
https://github.com/SerbiaStrong-220/space-station-14/pull/1889#issue-2534311998 исправлено
