### ISSUE TITLE
Ревенант может отстегивать кукол из невидимости

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1901]
### Описание

На данный момент ревенант может отстегивать кукол через открытие контекстного меню (пкм), чего быть не должно

### Шаги воспроизведения

1. Быть ревенантом
2. Кликнуть ПКМ по пристегнутой к чему-либо кукле и выбрать действие "отстегнуть"
3. Наблюдаем баг

### Скриншоты

![image](https://github.com/user-attachments/assets/21eb8bce-475c-41f0-b333-0a9b55f24583)

**Comment by UnknownSS220** [comment]
Данный баг удалось воспроизвести, ожидайте фикса.
