### ISSUE TITLE
Дубинки в разряженном состоянии

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1903]
### Описание

Дубинка и станпрод при разряженном состоянии станит

### Шаги воспроизведения

1. Выключить дубинку
2. Кинуть или ударить какую-то сущность

**Comment by Tris0r** [comment]
Баг воспроизводится.

**Comment by ReeZer2** [comment]
Не воспроизводится, можно закрывать

**Comment by Ady4ik** [comment]
Неактуально
