### ISSUE TITLE
Термалы раздевают куклу 

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1945]
### Описание

![image](https://github.com/user-attachments/assets/82c172e3-24c6-4190-bb04-defcf2a64f99)
Не понятно как воспроизвести, но репортов было много. 

https://discord.com/channels/1097181193939730453/1288624774121263185/1288624774121263185

**Comment by OwlMe1steR** [comment]
**Итоги**
Проблема наблюдается на всех доступных визорах (термальные очки охраны, термальные визоры и др.).

Когда надеваешь очки, все женские модели персонажей отображаются без одежды, в то время как мужские остаются одетыми, независимо от того, какую экипировку они носят (за исключением скафандров, которые остаются видимыми).

**Comment by Bomjojuk** [comment]
@Alwayswannahunt/@ReeZer2 
Вставай Шан Цунг, ты должен вспахать 100 тысяч багфиксов

**Comment by Alwayswannahunt** [comment]
> @Alwayswannahunt /@ReeZer2 Вставай Шан Цунг, ты должен вспахать 100 тысяч багфиксов

Не повторилось на локалке, скил ишью

**Comment by Ady4ik** [comment]
Недостаточно данных для решения ишуе.

**Comment by Bomjojuk** [comment]
Не ну я в ахуе
