### ISSUE TITLE
Total Black

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#1951]
### Описание

При игре на сервере в какой-то момент пропасть управление/опустеть экран, при этом возможно сохраняется возможность писать в чат(не всегда). У @.tekkirin есть логи и запись этого момента с госта. 

### Шаги воспроизведения

-

**Comment by Tris0r** [comment]
Логи и запись нужно прикладывать сразу.

**Comment by Tris0r** [comment]
Закрываем.

**Comment by stalengd** [comment]
Закрываем пока не появится подробностей по подобным багам, причём потенциально приводить к такому исходу могут разные баги.
