### ISSUE TITLE
Сломанное наложение слоёв на женские пешки

### ISSUE THREAD

**Issue by EstKemran** [SerbiaStrong-220/space-station-14#1953]
### Описание

На женских персонажах не отображается наложение слоёв через клозинг визиализутор, насколько я понимаю

  - type: Clothing
    clothingVisuals:
      jumpsuit:
      - state: equipped-INNERCLOTHING
      - ***state: trinkets-equipped-INNERCLOTHING***
     
Тот же инханд визуализтор исправно работает

### Шаги воспроизведения

1. Одеть одежду (стандартные разноцветные комбинезоны & водолазки)
2. Увидеть, что не отображается дополнительный слой (на мужских пешках исправно работает)

### Скриншоты

![изображение](https://github.com/user-attachments/assets/c393e37e-35b1-4959-bd42-63bda7368492)

**Comment by EstKemran** [comment]
Не актуально, оффы пофиксили. ПР не найду
![изображение](https://github.com/user-attachments/assets/3465bc6b-f440-4cb6-9ff7-f3ccc539c270)

**Comment by OwlMe1steR** [comment]
**Итог**

Раз пофиксили, значит пофиксили.
