### ISSUE TITLE
Рипли в клешне рипли

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1974]
### Описание

На данный момент будучи в рипли можно взять в клешню другую рипли и нести в хранилище клешни.
Ишуе по данному трекеру: https://discord.com/channels/1097181193939730453/1290014072149901474

### Шаги воспроизведения

1. сесть куклой в рипли
2. Делаем попытку взять в гидр. клешню другого меха и наблюдаем баг

**Comment by Ady4ik** [comment]
Проверено, 
баг воспроизвелся на обычной гидравлической клешне, на маленькой не пробовал.
