### ISSUE TITLE
Шатание клоунских ботинок

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#1976]
### Описание

На данный момент шатание клоунских ботинок крайне странно работает, так как в какой-то момент носитель может начать шататься даже пока лежит или сидит. (предположительно нет нормальной проверки идет ли кукла)

ТРЕБУЮТСЯ ТЕСТЫ

### Шаги воспроизведения

1. Быть в клоунских ботинках
2. Какое-то время ходить в них (точного способо воспроизведения не найдено)

**Comment by Surani1** [comment]
https://github.com/space-wizards/space-station-14/pull/32652

**Comment by UnknownSS220** [comment]
проверил, теперь анимация у клоунских ботинок удалена, считаю выполненым. Удачи
