### ISSUE TITLE
Прикрепление камеры на сигвей (требует проверки актуальности)

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1984]
### Описание

Если на сигвее вылететь в космос и включить джет - камера начнёт лететь за сигвеем пока сам персонаж будет двигаться и подчиняться вам.

https://discord.com/channels/1097181193939730453/1283900839504773172/1283900839504773172

### Шаги воспроизведения

1. Сигануть на любом т/с в космос -> 2. Включить джет

### Скриншоты

![image](https://github.com/user-attachments/assets/844012af-7316-4888-b085-cb96d7f6d028)

**Comment by Ady4ik** [comment]
проверено на квадроцикле, человек отцепляется, камера остается на человеке.
Отложено до повторного.
