### ISSUE TITLE
Дюп поз-мозга (нуждается в проверке актуальности)

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1985]
### Описание

Если борг встанет на обломок и тот пропадёт - с него выпадет ещё 1 мозг

https://discord.com/channels/1097181193939730453/1285092628269891614/1285092628269891614

### Шаги воспроизведения

1. Зайти за борга на замагниченный обломок -> 2. Дождаться его исчезновения

**Comment by Ady4ik** [comment]
Проверил: не гибает ни уриста, ни борга.
Отложено до повторного
