### ISSUE TITLE
Гарнитуры и дубликаты (проверить на актуальность) 

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1986]
### Описание

Если надеть гарнитуру, а вторую положить в карман - то сообщения начинают дублироваться, ты начинаешь слышать каналы что не присущи гарнитуре в ухе, но присущи гарнитуре в кармане, а если убрать гарнитуру из кармана - ты не видишь сообщений в рации

### Шаги воспроизведения

1. Надеть одну гарнитуру в ухо (например РНД) -> 2. Надеть вторую гарнитуру уже в карман (например СБ) 3. Слушать, трогать, говорить

**Comment by Ady4ik** [comment]
Проверил, неактуально.
Если появится способ воспроизведения - попрошу реопнуть ишуе.
![image](https://github.com/user-attachments/assets/00cef956-f7e1-4a03-bf45-a5f0bbbd736a)
