### ISSUE TITLE
Пояс медика (нужна проверка на актуальность)

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#1993]
### Описание

Из информации известно что если положить в пояс медика медикаменты они исчезают.

https://discord.com/channels/1097181193939730453/1281952329872183308/1281952329872183308

### Шаги воспроизведения

1. Положить в пояс медика медикаменты (больше информации нет)

**Comment by Ady4ik** [comment]
неактуально. Все пихается.
Если будет способ воспроизведения - попрошу реопнуть ишуе 
![image](https://github.com/user-attachments/assets/0a8a2a21-56a8-4e05-aa12-9df19a797356)
