### ISSUE TITLE
Галопроектор и пояса (проверка актуальности

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2009]
### Описание

Галопроектор атмоса можно положить в пояс охраны alt + E (Так же проверить другие пояса на другие галопроекторы)

https://discord.com/channels/1097181193939730453/1286041890747187261

### Шаги воспроизведения

1. Надеть пояс (проверить все) и взять в руку галопроектор атмосов (и не только) -> 2. alt + E

**Comment by Tris0r** [comment]
Голопроектор атмосов можно положить в пояса:
- ГСНа
- СБ
