### ISSUE TITLE
Нимфы и кудза (проверка актуальности)

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2011]
### Описание

Нимф замедляет кудза. (для сводки - дионы это растения. Кудза не замедляет дион. Нимфа производное дионы)

https://discord.com/channels/1097181193939730453/1286406366986240021

### Шаги воспроизведения

1. Зайти за нимфу в кудзу

**Comment by UnknownSS220** [comment]
проверено - кудза замедляет нимф, ожидайте исправления.
