### ISSUE TITLE
нельзя поменять местами или добавить элементы хотбара сбоку из меню действий

### ISSUE THREAD

**Issue by Glek3197** [SerbiaStrong-220/space-station-14#2017]
### Описание

после недавнего апстрима нельзя менять местами элементы хотбара с действиями или добавлять туда элементы из меню действий.

### Шаги воспроизведения

1. навести мышку на элемент хотбара 2. зажать мышку и перетянуть на другой элемент хотбара 3. элемент не перетягивается, вместо этого он активируется

**Comment by Tris0r** [comment]
Баг воспроизводится.

**Comment by DexlerXD** [comment]
исправлено в апстриме
