### ISSUE TITLE
Майнлдслейв работает сквозь МЩ

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#2031]
### Описание

Майндслейв работает даже если МЩ воткнут обратно, а не должен.

### Шаги воспроизведения

1. Вынуть МЩ
2. Воткнуть майндслейв
3. Воткнуть МЩ обратно (в идеале после этого шага промывка мозгов должна сбрасываться)

### Скриншоты

![image](https://github.com/user-attachments/assets/1f798339-5d3a-4454-87ce-e1a027d103c2)

**Comment by Alwayswannahunt** [comment]
Так и задумано.
Решать проблемы со слейвом нужно, но не убирая возможность слейвить сб/кэпа.

**Comment by gogenych** [comment]
> Так и задумано. Решать проблемы со слейвом нужно, но не убирая возможность слейвить сб/кэпа.

это и есть решение всех проблем с майндслейвом

**Comment by Alwayswannahunt** [comment]
> > Так и задумано. Решать проблемы со слейвом нужно, но не убирая возможность слейвить сб/кэпа.
> 
> это и есть решение всех проблем с майндслейвом. У тебя останется возможность слейвить кого угодно, только ты не сможешь потом нацепить на них мщ. ЧТО ЛОГИЧНО, ведь мщ подразумевает что член экипажа не имеет промытых мозгов.

Ты мне лором код объясняешь или что?
Если так, то МЩ не обеспечивает защиты от промывки мозгов в прошлом.

Если ты так пытаешься спросить что ещё можно сделать, то вполне можно повесить странное произношение слов, тряску, галлюцинации и тд. Чтобы человек с промытыми мозгами отличался от остальных, но для того, чтобы это понять нужно с ним взаимодействовать.
