### ISSUE TITLE
Проблемы с именами воксов

### ISSUE THREAD

**Issue by stalengd** [SerbiaStrong-220/space-station-14#2067]
### Описание

![image](https://github.com/user-attachments/assets/a52ced65-6e6b-400e-9511-45d2dda44a12)

**Comment by Tris0r** [comment]
Умер от смысловой нагрузки.

**Comment by TryHardo7** [comment]
Посмотрел в коде, имена воксов нормальные, результатом чего стало имя на скрине непонятно, вероятно ошибка пользователя, можно забить я полагаю
[vox_names.txt](https://github.com/user-attachments/files/17355777/vox_names.txt)

**Comment by EstKemran** [comment]
1. Не воспроизводиться не на локалке, не на сервере.
2. Достоверное, на мой взгляд, объяснение:
1.1. Игрок создал персонажа - арахнида (Филодромус Валкенаери - в датасетах арахнидов);
1.2. Поменял расу с арахнида на вокса;
1.3. Не поменял имя;
1.4. Игрок играет на воксе с именем арахнида.
