### ISSUE TITLE
DebugAssertException крашит локальный сервер

### ISSUE THREAD

**Issue by lexaSvarshik** [SerbiaStrong-220/space-station-14#2110]
### Описание

При внесении любого диска очков на сервер РНД сервер крашит (локальный сервер. На реальном не проверялось)

### Шаги воспроизведения

1. Тыкнуть диском очков по серверу рнд

### Скриншоты

![изображение](https://github.com/user-attachments/assets/4f6ab641-b14c-40e5-8538-ed9857ecbb6f)

**Comment by lexaSvarshik** [comment]
Вероятно, баг комплексный, и краши бывают по разным причинам. К примеру, мне крашнуло сервер после того как я сменил карту на Аксиому (код ошибки был иной)

**Comment by lexaSvarshik** [comment]
Ещё один странный краш. Путь воспроизведения - попытаться казнить себя любым предметом (казнь других работает нормально)
![изображение](https://github.com/user-attachments/assets/231d5b23-543b-499b-b041-001bb7e1726a)

**Comment by lexaSvarshik** [comment]
Я честно не понимаю что сломано. Сейчас я попытался за ниана ударить кулаком гориллу.
![изображение](https://github.com/user-attachments/assets/3f02bcfa-a1e8-4228-934b-168ec60f341c)

**Comment by Ady4ik** [comment]
Не наши заботы, увы
