### ISSUE TITLE
Сломанное отображение наигранного времени

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#2113]
### Описание

Пост по трекеру: https://discord.com/channels/1097181193939730453/1296977312155303956
На данный момент, после изменения отображения времени игры от официалов, отображение наигранного времени на конкретных ролях через меню "статистика" Полностью сломано (смотреть скриншот ниже) 

### Шаги воспроизведения

1. В меню редактуры персонажа открыть меню "статистика"
2. Наблюдаем ошибку

### Скриншоты

![95b66f16999933d7](https://github.com/user-attachments/assets/74188b3d-d176-4656-a1d3-c7cc6d6cdf23)

**Comment by Bomjojuk** [comment]
https://github.com/SerbiaStrong-220/space-station-14/pull/2115
Фикситься пром, закрыто

**Comment by stalengd** [comment]
> #2115 Фикситься пром, закрыто

Так PR ещё не закрыт...
