### ISSUE TITLE
Маскировочный проектор

### ISSUE THREAD

**Issue by Bomjojuk** [SerbiaStrong-220/space-station-14#2119]
### Описание

На данный момент с маскировочным проектором существует как минимум два бага: 
Критический: при маскировке проектором в ЛЮБОЙ вендомат, отображение мира вокруг со стороны клиента начинает ломаться, делая полностью неиграбельным (видео ниже) 
Второй: при маскировке в любой лат, который имеет анимацию вставки в него материалов, спрайт замаскированного игрока будет проигрывать эту анимацию на повторе, без возможности остановить

### Шаги воспроизведения

Первый баг: 
1. Попытаться замаскироваться в любой вендомат
2. Наблюдаем баг
Второй: 
1. Маскируемся в любой лат, имеющий анимацию пополнения
2. Наблюдаем эффект (скриншот ниже)

### Скриншоты

Видео первого бага: https://cdn.discordapp.com/attachments/1250396418552893450/1297183639142137886/Space_Station_14_-_SS220_Station_RU_19-10-2024_18-03-52.mp4?ex=6714ffe8&is=6713ae68&hm=652aada5e88ec34e3e36381b3fe6f03530deaecfe7e199b77116edea04f8d138& (видео слишком большое, увы)

Второй баг: 
![image](https://github.com/user-attachments/assets/61c2dc81-19c1-4930-a83a-5eb04aaa5ab0)

**Comment by UrPrice** [comment]
Почему тут тег ревью? Какое ревью?
