### ISSUE TITLE
Неправильная статистика наигранного времени 

### ISSUE THREAD

**Issue by Heidem1** [SerbiaStrong-220/space-station-14#2121]
### Описание

В лобби неправильно отображается статистика времени игрока

Связанно с рефактором времени от оффов

### Шаги воспроизведения

1. Зайти в лобби
2. Открыть окно редактирование персонажа
3. Открыть статистику игрока
4. Увидеть некоректное отображение времени в статистике

### Скриншоты

![image](https://github.com/user-attachments/assets/e2f9b0cb-487c-4ce3-ab52-65b62ebd9ac0)

**Comment by ReeZer2** [comment]
Пофикшено.
