### ISSUE TITLE
Неправильное отображение времени для ролей

### ISSUE THREAD

**Issue by Heidem1** [SerbiaStrong-220/space-station-14#2122]
### Описание

В лобби неправильно отображается время необходимое для разблокировки ролей/лодаута

Вероятно связанно с рефактором времени от оффов

### Шаги воспроизведения

1. Зайти в лобби
2. Открыть редактор персонажа
3. Навести курсор за закрытые роли/опции
4. Увидеть неправильное время

### Скриншоты

![image](https://github.com/user-attachments/assets/a2e918fa-8315-4241-a0af-104966a6cd2f)
на скриншоте наигранно 0 часов на авд

**Comment by ReeZer2** [comment]
Пофикшено
