### ISSUE TITLE
Разгерма не убивает сухожилия 

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2125]
### Описание

Разгерметизация не может уничтожить сухожилия из-за чего её почти невозможно убрать. 

https://discord.com/channels/1097181193939730453/1287060284631941211/1287060284631941211

### Шаги воспроизведения

1. Поставить сухожилия -> 2. Подождать её полного роста -> 3. Создать разгерму в комнате

**Comment by UrPrice** [comment]
Почему тут тег ревью? Какое ревью?

**Comment by ReeZer2** [comment]
Баг не воспроизводится, сухожилия уничтожаются разгермой
