### ISSUE TITLE
Пропажа часов

### ISSUE THREAD

**Issue by Ady4ik** [SerbiaStrong-220/space-station-14#2133]
### Описание

В статистике произошло практически полный откат часов у всех игроков.

### Шаги воспроизведения

Необходимо уточнение информации, как и когда это произошло.

### Скриншоты

![image](https://github.com/user-attachments/assets/63168e90-c7c3-48d0-b931-2f2c8732b6c2)

**Comment by Alwayswannahunt** [comment]
Никуда время игроков не делось. Офы решили использовать стандартный способ превращения TimeSpan в строку, но он не поддерживает суммарный вывод часов, поэтому игроки и видят часы в промежутке от 0 до 23.

**Comment by Ady4ik** [comment]
> Никуда время игроков не делось. Офы решили использовать стандартный способ превращения TimeSpan в строку, но он не поддерживает суммарный вывод часов, поэтому игроки и видят часы в промежутке от 0 до 23. 

Значит нужно добавить конвертирование в дни? Иначе это выглядит, как будто они пропали

**Comment by stalengd** [comment]
Создал ишуй на апстриме, там же создал фикс https://github.com/space-wizards/space-station-14/issues/32973
