### ISSUE TITLE
Ковры ставятся под друг-друга

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2154]
### Описание

Ковры (которые от ковролина и просто устанавливаемые за счёт предмета) можно ставить друг на друга, при этом сервер и ПК игроков нагружаются всё так же прорисовывая каждый ковёр. Надо убрать такую возможность
PS: сколько тут слов ковёр?

### Шаги воспроизведения

1. Поставить ковёр на ковёр/распылить на уже существующий ковёр ковролин

**Comment by Tris0r** [comment]
Воспроизводится.
