### ISSUE TITLE
Плитки пола при бросании игнорируют резисты цели

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#2209]
### Описание

Плитки пола игнорируют резисты на кукле.

### Шаги воспроизведения

1. Кинуть плитку в куклу с броней плитку
2. Просканировать куклу
3. Работают-ли резисты?

**Comment by lexaSvarshik** [comment]
![изображение](https://github.com/user-attachments/assets/94c4b8cf-314a-42fb-947b-55578a8735d6)
Не игнорирует
