### ISSUE TITLE
Сломанный поворот строений 2

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2241]
### Описание

При стройке место указанной стороны расположения объект смотрит в одну и ту же сторону. 
Из известных - полки, диагональные окна. (возможно надо ещё искать баги на эту тему)

https://discord.com/channels/1097181193939730453/1307265603505098763/1307265603505098763

### Шаги воспроизведения

1. в меню стройки выбрать диагональную решётку -> 2. Построить её

### Скриншоты

![image](https://github.com/user-attachments/assets/379787ad-7e55-442b-a0d5-e7aa6b4b43f0)

**Comment by psykana** [comment]
Шлюзы тоже
