### ISSUE TITLE
Перчатки ниндзи перестают работать

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2244]
### Описание

После замены батареи (и даже просто бегая) перчатки перестают высасывать энергию и заряжать костюм, обречая ниндзю на смерть

https://discord.com/channels/1097181193939730453/1304907154653974528/1304907154653974528

### Шаги воспроизведения

1. Заменить батареи и просто поделать что либо за ниндзю и проверить работу перчаток

**Comment by Kirus59** [comment]
Не воспроизводится
