### ISSUE TITLE
Эмодзи не распознают частоту

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2245]
### Описание

Когда хочешь написать что либо в рацию ":р ауу, я тута" ":о КЛОУН С НОЖОМ" место отправки в рацию :р и :о расцениваются как эмодзи. Из решений вижу, что эмоцию можно ставить только в конце, а если спереди будет текст то она отправит всё либо в рацию, либо вообще просто скажет в "рядом"

https://discord.com/channels/1097181193939730453/1303387818579595275/1303387818579595275

### Шаги воспроизведения

1. Написать в рацию любую фразу с :р вначале и пробелом после него

**Comment by ReeZer2** [comment]
На локалке не воспроизводится
