### ISSUE TITLE
Правила не открываются

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2246]
### Описание

Главы правил не могут открыться по новой механики оффов (через ссылки эти)

https://discord.com/channels/1097181193939730453/1303106932696944651/1303106932696944651

### Шаги воспроизведения

1. Открыть правила и тыкать на разные главы правид

### Скриншоты

![image](https://github.com/user-attachments/assets/d630106d-fd02-4d64-8775-640b03270fc0)

**Comment by ReeZer2** [comment]
Протестировано на локалке, всё работает. Можно закрывать.

**Comment by stalengd** [comment]
> Протестировано на локалке, всё работает. Можно закрывать.

Это надо бы на боевом сервере проверить.

**Comment by ReeZer2** [comment]
> > Протестировано на локалке, всё работает. Можно закрывать.
> 
> Это надо бы на боевом сервере проверить.

На сервере Персеус всё пашет
