### ISSUE TITLE
Вишнёвый пирог не подходит к запросам

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2250]
### Описание

Вишнёвый пирог не подходит для запроса на 4 пирога для НТ

https://discord.com/channels/1097181193939730453/1299721030650167401/1299721030650167401

### Шаги воспроизведения

1. Засунуть пироги в ящик с запросом и проверить на собранность заказа

### Скриншоты

![image](https://github.com/user-attachments/assets/3a1cbc37-6406-40eb-9e47-6098bf0b439e)
![image](https://github.com/user-attachments/assets/10fedbb2-898b-4fb9-91db-23b034ed5389)

**Comment by ReeZer2** [comment]
Только что протестил, с вишнёвыми пирогами всё отлично, считается как запрос и продается.
