### ISSUE TITLE
ИИ видит через стелс-коробку

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2253]
### Описание

Меди-боты и другие ИИ могут видеть через коробку и что либо делать с тобой.

https://discord.com/channels/1097181193939730453/1297290895707734086/1297290895707734086

### Шаги воспроизведения

1. Закрыть стелс-коробку перед меди-ботом

**Comment by ReeZer2** [comment]
Блин, забыл тегнуть в пр-е этот ишуе, можно закрывать.

https://github.com/SerbiaStrong-220/space-station-14/pull/2303
