### ISSUE TITLE
ТТС не меняется в голосовой маске

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2256]
### Описание

ТТС при выборе не меняется, оставляя игрока с первоначальным голосом.

https://discord.com/channels/1097181193939730453/1295019239366856724/1295019239366856724

### Шаги воспроизведения

1. В меню маски вписать имя и голос -> 2. Сказать в чат что-нибудь

**Comment by ReeZer2** [comment]
Проверено на сервере, голос меняется.
