### ISSUE TITLE
Шлюзы гидропоники

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2298]
### Описание

Шлюзы у гидропоники из билда оффов - надобно их переделать на свой лад (это уже сделали, осталось всё добавить)

https://discord.com/channels/1097181193939730453/1312819789668028546/1312819789668028546

### Шаги воспроизведения

1. Заспавнить шлюз гидропоники

### Скриншоты

Что надо:
![image](https://github.com/user-attachments/assets/12ec575b-3895-45e3-9a80-fa0d63a93322)
Что сейчас:
![image](https://github.com/user-attachments/assets/5532c4e6-14fd-4290-9e10-7985e54f472e)

**Comment by Tris0r** [comment]
Лично сделаю за выходные.

**Comment by stalengd** [comment]
#2309
