### ISSUE TITLE
Предметики в стеночке застрявунькают

### ISSUE THREAD

**Issue by Gun-Done** [SerbiaStrong-220/space-station-14#2332]
### Опишите кратко о том, какую проблему вы обнаружили

Если из шкафчика в меде под палатами взять что-то, оно застрянет в стене

### Прикрепите изображение описанной вами проблемы

![20241209113533_1](https://github.com/user-attachments/assets/8a847e79-332c-40de-8036-5bd928e40d06)

**Comment by UrPrice** [comment]
@stalengd лейблы бы

**Comment by Gun-Done** [comment]
я видел, как этот шкаф нормально работал и не засовывал предметы в стену
