### ISSUE TITLE
Травматическая граната исчезает

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2340]
### Описание

Если держа травм. гранату в руке кликнуть по другой гранате - она остаётся в буфере гранаты. А если взорвать оставшуюся гранату - после взрыва вылетят все другие и тоже взорвуться.

### Шаги воспроизведения

1. Взять две травм. гранаты -> 2. Кликнуть по гранате

### Скриншоты

Спасибо спукмурке за баг;3

https://github.com/user-attachments/assets/e4dfb7b9-db1e-454f-8589-6c8c9e00884e

https://github.com/user-attachments/assets/23ef3104-e37b-45c7-8781-b6e9b57f10cb

**Comment by Tris0r** [comment]
**_ВОСПРОИЗВОДИТСЯ!_**
Как будто тут нужно высокий приоритет поставить...

**Comment by Tris0r** [comment]
Кто возьмётся - проблема с компонентом FlashOnTrigger.
