### ISSUE TITLE
Консоль связи

### ISSUE THREAD

**Issue by Mishics** [SerbiaStrong-220/space-station-14#2352]
### Описание

В описание консоли связи неправильная приписка "...посредством клавиатуры...", при этом немые говорят своим голосом. Нужно добавить приписку про микрофон не убирая клавиатуру. Так же исправить баг связанный с голосом немых.

https://discord.com/channels/1097181193939730453/1317041442492907591/1317041442492907591

### Шаги воспроизведения

1. Осмотреть консоль связи

### Скриншоты

![image](https://github.com/user-attachments/assets/b2555a91-e7f2-4cf1-8652-6ad86cd52a1c)

**Comment by Tris0r** [comment]
@stalengd закрываем.
