### ISSUE TITLE
Нагрудная камера и ИИ

### ISSUE THREAD

**Issue by Dictator-hub** [SerbiaStrong-220/space-station-14#2361]
### Описание

Нагрудные камеры не работают на персонаже в слоте и не зависят от электричества. Нужно добавить в камеру слот для батарейки. Одобрил и протестил ЮрПрайс, запись теста у него тоже.

### Шаги воспроизведения

1. Активировать камеру в руке
2.  Поместить её в слот шеи
3. Посмотреть через око ИИ результат

**Comment by Tris0r** [comment]
Сделаю.

**Comment by Tris0r** [comment]
СТОП. А зачем это вообще сюда залили?

**Comment by Dictator-hub** [comment]
Простите, был под пивом. Щас в таски перенесу
