### ISSUE TITLE
[MI] Отсутствие голопадов на АСН "Севастополь"

### ISSUE THREAD

**Issue by dalvis-v** [SerbiaStrong-220/space-station-14#2402]
### Выберите игровую карту

АСН "Севастополь"

### Опишите кратко о том, какую проблему вы обнаружили

На АСН "Севастополь" полностью отсутствуют голопады для связи со станциями, невозможно отыгрывать ОЦК для связи со станциями без факса.

### Прикрепите изображение описанной вами проблемы

![image](https://github.com/user-attachments/assets/2646d8de-8624-4904-bd69-407b9f1c16bd)

**Comment by lexaSvarshik** [comment]
А разве ОЦК не должен связываться исключительно по факсу и в крайних случаях по консоли? А если уж совсем прижмёт, то отправлять поцка

**Comment by stalengd** [comment]
Дубликат #2393
