### ISSUE TITLE
Проблемы с дистрой Франка

### ISSUE THREAD

**Issue by Jokerrussio** [SerbiaStrong-220/space-station-14#2406]
### Выберите игровую карту

Frankenstein

### Опишите кратко о том, какую проблему вы обнаружили

В комнате с газодобытчиками азота есть кислород, а в комнате с кислородом - азот. СМЭСЫ у СМа и синги не перегружены раундстартом.  Насчёт комнат с газодобычтиком всё очевидно. Убрать Азот из кислорода и кислород с азота. Зачем? Нуэээ...С появлением СМа в массы появились мотивы варить тритий и фрезон, ибо появился источник плазмы... По СМЭСАМ не совсем понял. Так и задумано? Просто из-за этого приходится либо запускать ДАМ и тратить топливо, либо спешить с запуском

### Прикрепите изображение описанной вами проблемы

![image](https://github.com/user-attachments/assets/7ed9878b-e9a3-4e38-991b-3c346ae00807)
![image2](https://github.com/user-attachments/assets/392d4125-61d4-4dab-b549-7606d9ef8fce)
![image3](https://github.com/user-attachments/assets/73d9d63b-893b-4325-8981-51d0f2ed38f9)

**Comment by UrPrice** [comment]
Да, так как СМЭСы не питают основную часть станцию, то они не перегружены. Оверчарджатся только СМЭСы центральных энергоблоков на станциях. При желании, можете просто привести св провод к схеме того участка, в котором требуется подать питание на лкп. Везде он довольно легко подводится, как я помню.

С камерами косяк, поправлю, спасибо. Атмосфиксмаркеры не расставил.
