### ISSUE TITLE
Кукла уходит в госты если удалить кресло-каталку под ней

### ISSUE THREAD

**Issue by Tris0r** [SerbiaStrong-220/space-station-14#2409]
### Описание

Кукла уходит в госты если удалить кресло-каталку под ней

### Шаги воспроизведения

1. Спавним или находим кресло-каталку
2. Садим на неё куклу
3. Удаляем кресло-каталку

**Comment by ReeZer2** [comment]
Работает со всеми видами стульев, и всего к чему можно пристегнуться. Но опять же, это может сделать только админ
