### ISSUE TITLE
Перестановка в комнате синего щита

### ISSUE THREAD

**Issue by Abiergo** [SerbiaStrong-220/space-station-14#2411]
### Выберите игровую карту

Frankenstein

### Опишите кратко о том, какую проблему вы обнаружили

Добавить настенную зарядку в комнату синего щита для его нового дополнения в виде энергоружья, и переставить как на скриншоте консоль с ящиком, как фам идея?

### Прикрепите изображение описанной вами проблемы

![image](https://github.com/user-attachments/assets/23d9632e-c72f-4e26-a3e0-5531cbb30929)

**Comment by Abiergo** [comment]
Ну и если не нравится та пустота в том углу то можно припудрить её... ЦВЕТОЧКОМ
![image](https://github.com/user-attachments/assets/22bedb22-50b2-4d2a-8a2c-ed67cdda1b03)
Или так
![image](https://github.com/user-attachments/assets/0347c8e7-84b9-4528-9286-24bb4892f1a0)

**Comment by anders0n9** [comment]
Цветок ужасно выглядит в том месте. Остальное +- нормально, потому как решит куратор франка. Ожидайте обновления через 10 месяцев🤙🏻
